%% check 'main.m' has run (and run it if not)
toso2021_maincheck;

%% ROI settings

% roi definition
roi = [-500,t_set(end)];
padded_roi = roi + [-1,1] * .05 * range(roi);
n_bins = range(padded_roi) / psthbin;
time = linspace(padded_roi(1),padded_roi(2),n_bins);

% preallocation
zscore_weights = nan(n_bins,n_neurons);
ref_psths = nan(n_bins,n_neurons);
psths = nan(n_bins,n_neurons,n_contrasts);

%% subject selection
subject_flags = ismember(subjects,subject_set);

%% construct s1-aligned psths

% iterate through neurons
for nn = 1 : n_neurons
    progressreport(nn,n_neurons,'parsing neural data');
    neuron_flags = data.NeuronNumb == flagged_neurons(nn);
    ref_spike_flags = ...
        valid_flags & ...
        subject_flags & ...
        neuron_flags;
    if sum(ref_spike_flags) == 0
        continue;
    end
    
    % fetch spike counts & compute spike rates
    ref_spike_counts = data.FR(ref_spike_flags,:);
    ref_spike_rates = data.SDF(ref_spike_flags,:);
    ref_n_trials = size(ref_spike_counts,1);
    
    % S1-aligned spike rates
    ref_alignment = ...
        pre_init_padding + ...
        pre_s1_delay(ref_spike_flags);
    ref_alignment_flags = ...
        padded_time >= ref_alignment + padded_roi(1) & ...
        padded_time < ref_alignment + t1(ref_spike_flags);
    ref_chunk_flags = ...
        padded_time >= ref_alignment + padded_roi(1) & ...
        padded_time < ref_alignment + padded_roi(2);
    ref_spkrates = ref_spike_rates';
    ref_spkrates(~ref_alignment_flags') = nan;
    ref_spkrates = reshape(...
        ref_spkrates(ref_chunk_flags'),[n_bins,ref_n_trials])';
    
    % compute observations weights
    zscore_weights(:,nn) = sum(~isnan(ref_spkrates));
    
    % compute mean spike density function
    ref_psths(:,nn) = nanmean(ref_spkrates,1);
    
    % iterate through contrasts
    for ii = 1 : n_contrasts
        contrast_flags = contrasts == contrast_set(ii);
        spike_flags = ...
            valid_flags & ...
            subject_flags & ...
            neuron_flags & ...
            contrast_flags;
        if sum(spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        spike_counts = data.FR(spike_flags,:);
        spike_rates = data.SDF(spike_flags,:);
        n_trials = size(spike_counts,1);
        
        % S1-aligned spike rates
        alignment_onset = ...
            pre_init_padding + ...
            pre_s1_delay(spike_flags);
        alignment_flags = ...
            padded_time >= alignment_onset + padded_roi(1) & ...
            padded_time < alignment_onset + t1(spike_flags);
        chunk_flags = ...
            padded_time >= alignment_onset + padded_roi(1) & ...
            padded_time < alignment_onset + padded_roi(2);
        spkrates = spike_rates';
        spkrates(~alignment_flags') = nan;
        spkrates = reshape(...
            spkrates(chunk_flags'),[n_bins,n_trials])';
        
        % compute mean spike density function
        psths(:,nn,ii) = nanmean(spkrates,1);
    end
end

%% normalization
mus = nanmean(ref_psths,1);
sigs = nanstd(ref_psths,0,1);

% z-scoring
zpsths = (psths - mus) ./ sigs;

%% plot overall modulation

% figure initialization
fig = figure(figopt,...
    'name',['average_activity_s1_',contrast_str]);

% axes initialization
xxtick = unique([0;roi';t_set]);
xxticklabel = num2cell(xxtick);
xxticklabel(xxtick > 0 & xxtick < t_set(end)) = {''};
axes(axesopt.default,...
    'clipping','off',...
    'xlim',roi + [-1,1] * .05 * range(roi),...
    'xtick',xxtick,...
    'xticklabel',xxticklabel,...
    'ylim',[-.75,.5]+[-1,1]*.05*1.25,...
    'ytick',[-.75,0,.5]);
xlabel('Time since S_1 onset (ms)');
ylabel('Firing rate (z-scored)');

% graphical object preallocation
p = gobjects(n_contrasts,1);
mu_gobjs = gobjects(n_contrasts,n_t);
sem_gobjs = gobjects(n_contrasts,n_t);

% zero lines
plot([1,1]*0,ylim,...
    'color','k',...
    'linestyle',':');
plot(xlim,[1,1]*0,...
    'color','k',...
    'linestyle',':');

% iterate through contrasts
for ii = 1 : n_contrasts
    contrast_flags = contrasts == contrast_set(ii);
    trial_flags = ...
        valid_flags & ...
        contrast_flags;
    
    % compute surviving trial counts (through time)
    time_mat = repmat(...
        padded_roi(1) + psthbin : psthbin : padded_roi(2),n_total_trials,1);
    surviving_trial_counts = sum(time_mat(trial_flags,:) <= t1(trial_flags));
    t1offset_idcs = find([diff(surviving_trial_counts) ~= 0, true]);
    
    % compute modulation stats
    nan_flags = all(isnan(psths(:,:,ii)),2);
    onset_flags = time <= 0 & [time(2:end),nan] > 0;
    X = zpsths(~nan_flags,:,ii);
    x_mu = nanmean(X,2);
    x_sig = nanstd(X,0,2);
    x_sem = x_sig / sqrt(n_neurons);
    
    % patch s.e.m.
    sem_xpatch = [time(~nan_flags),fliplr(time(~nan_flags))];
    sem_ypatch = [x_mu(~nan_flags)-x_sem(~nan_flags);...
        flipud(x_mu(~nan_flags)+x_sem(~nan_flags))]';
    sem_apatch = [surviving_trial_counts(~nan_flags),...
        fliplr(surviving_trial_counts(~nan_flags))];
    sem_apatch = sem_apatch ./ max(sem_apatch) .* ...
        range(alphabounds_sem) + alphabounds_sem(1);
    if fadeifnoisy
        alpha_levels = unique(sem_apatch,'stable');
        n_alpha_levels = numel(alpha_levels);
        for aa = 1 : n_alpha_levels
            alpha_flags = sem_apatch == alpha_levels(aa);
            sem_gobjs(ii,tt) = patch(...
                sem_xpatch(alpha_flags),...
                sem_ypatch(alpha_flags),0,...
                'facealpha',alpha_levels(aa),...
                'edgecolor','none',...
                'facecolor',contrast_clrs(ii,:));
        end
    else
        sem_gobjs(ii,1) = patch(sem_xpatch,sem_ypatch,contrast_clrs(ii,:),...
            'facealpha',.25,...
            'edgecolor','none');
    end
    
    % patch average activity
    mu_xpatch = time(~nan_flags);
    mu_ypatch = x_mu(~nan_flags)';
    mu_ypatch(end) = nan;
    mu_apatch = surviving_trial_counts(~nan_flags);
    mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
        range(alphabounds_mu) + alphabounds_mu(1);
    if fadeifnoisy
        for tt = 1 : n_t
            try
                alpha_level = mu_apatch(t1offset_idcs(tt));
                alpha_flags = mu_apatch == alpha_level;
                mu_gobjs(ii,tt) = patch(...
                    [mu_xpatch(alpha_flags),nan],...
                    [mu_ypatch(alpha_flags),nan],0,...
                    'edgealpha',alpha_level,...
                    'edgecolor',contrast_clrs(ii,:),...
                    'facecolor','none',...
                    'linewidth',1.5);
            catch
            end
        end
    else
        mu_gobjs(ii,1) = plot(mu_xpatch,mu_ypatch,...
            'color',contrast_clrs(ii,:),...
            'linewidth',1.5);
    end
    
    % plot alignment onset
    p(ii) = plot(time(onset_flags),x_mu(onset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',7.5,...
        'markerfacecolor','w',...
        'markeredgecolor',contrast_clrs(ii,:));
    
    % iterate through stimuli
    for tt = 1 : n_t
        t1_flags = t1 == t_set(tt);
        trial_flags = ...
            valid_flags & ...
            contrast_flags & ...
            t1_flags;
        if sum(trial_flags) < 1
            continue;
        end
        
        % plot stimulus offset
        try
            alpha_level = mu_apatch(t1offset_idcs(tt));
            scatter(time(t1offset_idcs(tt)),x_mu(t1offset_idcs(tt)),50,...
                'linewidth',1.5,...
                'marker','o',...
                'markerfacealpha',alpha_level.^fadeifnoisy,...
                'markerfacecolor',contrast_clrs(ii,:),...
                'markeredgecolor','none');
        catch
        end
    end
end

% ui restacking
uistack([mu_gobjs(isgraphics(mu_gobjs)); ...
    sem_gobjs(isgraphics(sem_gobjs))],'bottom');
uistack(p,'top');

% legend
p1 = plot([1,1]*max(xlim)*2,[1,1]*max(ylim)*2,...
    'linewidth',1.5,...
    'linestyle','none',...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor','k');
p2 = plot([1,1]*max(xlim)*2,[1,1]*max(ylim)*2,...
    'linewidth',1.5,...
    'linestyle','none',...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','k',...
    'markeredgecolor','none');
legend([p1,p2],{'S_1 onset','S_1 offset'},...
    'fontsize',axesopt.default.fontsize*.9,...
    'location','southeast',...
    'box','off');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end