%% initialization
if ~exist('data','var')
    toso2021_wrapper;
end

%% neuron selection

% selected for being good examples of i2-modulation
if strcmpi(task_str,'duration')
    neurons2plot = [...
        21,35,38,62,72,100,130,205,206,215,224,...
        234,241,391,393,397,402,406,428,...
        441,459,462,470,473,526,544,566];
    neurons2plot = [...
        215,393,402,462,526];
elseif strcmpi(task_str,'intensity')
    neurons2plot = [...
        19,22,30,61,66,70,100,111,112,115,...
        166,238,243,260,344,408,410];
end
% neurons2plot = flagged_neurons;
n_neurons2plot = numel(neurons2plot);

%% version-dependent spike marker
version = ver('matlab');
if contains(version.Release,'2019')
    spike_marker = '.';
    spike_markersize = 1.5;
else
    spike_marker = '.';
    spike_markersize = 1.5;
end

%% construct Si-aligned, Ti- & Ii-split psths
ti_padd = [-500,0];

% iterate through neurons
for nn = 1 : n_neurons2plot
    progressreport(nn,n_neurons2plot,'parsing neural data');
    neuron_flags = data.NeuronNumb == neurons2plot(nn);
    
    % figure initialization
    fig = figure(figopt,...
        ...'windowstate','maximized',...
        'position',[600,1250,2400,460],...
        'name',sprintf('neuron_%i',neurons2plot(nn)));
    n_rows = 2;
    n_cols = 4;
    n_sps = n_rows * n_cols;
    sps = gobjects(n_sps,1);
    for ii = 1 : n_cols
        sps(ii) = subplot(n_rows,n_cols,ii);
        sps(ii+n_cols) = subplot(n_rows,n_cols,n_cols+ii);
    end
    xxtick = unique([ti_padd(1);-pre_t1_delay;0;t_set;t_set(end)+ti_padd(2)]);
    xxticklabel = num2cell(xxtick);
    xxticklabel(xxtick > 0 & xxtick < 1e3) = {''};
    set(sps,...
        axesopt.default,...
        'layer','top',...
        'plotboxaspectratiomode','auto',...
        'ylimspec','tight');
    set(sps(1+[0,n_cols]),...
        'xlim',[0,max(t_set)]+ti_padd,...
        'xtick',xxtick,...
        'xticklabel',xxticklabel);
    set(sps(2+[0,n_cols]),...
        'xlim',[0,isi],...
        'xtick',linspace(0,isi,5));
    set(sps(3+[0,n_cols]),...
        'xlim',[0,max(t_set)]+ti_padd,...
        'xtick',xxtick,...
        'xticklabel',xxticklabel);
    set(sps(4+[0,n_cols]),...
        'xlim',[0,post_s2_delay],...
        'xtick',[0,post_s2_delay]);
    xlabel(sps(1+n_cols),'Time since T_1 onset (s)');
    xlabel(sps(2+n_cols),'Time since T_1 offset (s)');
    xlabel(sps(3+n_cols),'Time since T_2 onset (s)');
    xlabel(sps(4+n_cols),'Time since T_2 offset (s)');
    ylabel(sps(1),'Firing rate (Hz)');
    ylabel(sps(2),'Firing rate (Hz)');
    ylabel(sps(3),'Firing rate (Hz)');
    ylabel(sps(4),'Firing rate (Hz)');
    ylabel(sps(1+n_cols),'Trial #');
    ylabel(sps(2+n_cols),'Trial #');
    ylabel(sps(3+n_cols),'Trial #');
    ylabel(sps(4+n_cols),'Trial #');
    
    % update aspect ratio
    for ii = 1 : n_sps
        set(sps(ii),...
            'plotboxaspectratio',[range(xlim(sps(ii)))/1e3*1.25,1,1]);
    end
    
    % preallocation
    s1_n_trial_counter = 0;
    isi_n_trial_counter = 0;
    s2_n_trial_counter = 0;
    t2_n_trial_counter = 0;
    s1_boundaries = nan(n_i,1);
    isi_boundaries = nan(n_t,1);
    s2_boundaries = nan(n_i,1);
    t2_boundaries = nan(n_t,1);
    
    % iterate through intensities
    for ii = 1 : n_i
        i1_flags = i1 == i_set(ii);
        s1_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            i1_flags;
        if sum(s1_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        s1_spike_counts = data.FR(s1_spike_flags,:);
        s1_spike_rates = conv2(...
            1,kernel.pdf,s1_spike_counts,'valid')' / psthbin * 1e3;
        s1_n_trials = size(s1_spike_counts,1);
        s1_n_tbins = n_tbins + range(ti_padd) * psthbin;
        
        % T1-aligned, T1-split spike rates
        s1_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(s1_spike_flags);
        s1_alignment_flags = ...
            valid_time >= s1_alignment_onset + ti_padd(1) & ...
            valid_time < s1_alignment_onset + t2(s1_spike_flags);
        s1_chunk_flags = ...
            valid_time >= s1_alignment_onset + ti_padd(1)& ...
            valid_time < s1_alignment_onset + max(t_set) + ti_padd(2);
        s1_spkrates = s1_spike_rates;
        s1_spkrates(~s1_alignment_flags') = nan;
        s1_spkrates = reshape(...
            s1_spkrates(s1_chunk_flags'),[s1_n_tbins,s1_n_trials])';
        
        % compute mean spike density function
        time2plot = ti_padd(1) + psthbin : psthbin : max(t_set) + ti_padd(2);
        time_flags = time2plot <= max(t_set) + ti_padd(2);
        s1_mu = nanmean(s1_spkrates(:,time_flags),1);
        s1_std = nanstd(s1_spkrates(:,time_flags),0,1);
        s1_trials_throughtime = sum(~isnan(s1_spkrates),1);
        s1_sem = s1_std ./ sqrt(s1_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(s1_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        s1_xpatch = [flagged_time,fliplr(flagged_time)];
        s1_ypatch = [s1_mu(~nan_flags)-s1_sem(~nan_flags),...
            fliplr(s1_mu(~nan_flags)+s1_sem(~nan_flags))];
        patch_alpha = [s1_trials_throughtime(~nan_flags),...
            fliplr(s1_trials_throughtime(~nan_flags))];
        patch_alpha = (patch_alpha - min(s1_trials_throughtime)) / ...
            range(s1_trials_throughtime);
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(1),s1_xpatch,s1_ypatch,i1_clrs(ii,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        s1_xpatch = flagged_time(~nan_flags);
        s1_ypatch = s1_mu(~nan_flags);
        s1_ypatch(end) = nan;
        patch_alpha = s1_trials_throughtime(~nan_flags);
        patch_alpha = (patch_alpha - min(s1_trials_throughtime)) / ...
            range(s1_trials_throughtime);
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(1),s1_xpatch,s1_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',i1_clrs(ii,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(1),time2plot(onset_flags),s1_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',i1_clrs(ii,:));
        
        % plot T1 raster
        s1_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(s1_spike_flags));
        s1_trial_idcs = (1 : s1_n_trials)' + s1_n_trial_counter;
        s1_trial_mat = repmat(s1_trial_idcs,1,n_paddedtimebins);
        s1_spike_trials = s1_trial_mat(s1_spike_counts >= 1);
        s1_spike_times = s1_time_mat(s1_spike_counts >= 1);
        trial_sorter = [t1(s1_spike_flags),prev_choices(s1_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + s1_n_trial_counter;
        s1_sorted_trials = resorted_idcs(s1_spike_trials - s1_n_trial_counter);
        plot(sps(1+n_cols),s1_spike_times,s1_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',spike_markersize,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = ti_padd(1) + [0,1,1,0] .* 50;
        ypatch = [.5,.5,s1_n_trials+.5,s1_n_trials+.5] + s1_n_trial_counter;
        patch(sps(1+n_cols),xpatch,ypatch,i1_clrs(ii,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        s1_n_trial_counter = s1_n_trial_counter + s1_n_trials;
        s1_boundaries(ii) = s1_n_trials;
    end
    
    % iterate through durations
    for tt = 1 : n_t
        t1_flags = t1 == t_set(tt);
        isi_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            t1_flags;
        if sum(isi_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        isi_spike_counts = data.FR(isi_spike_flags,:);
        isi_spike_rates = conv2(...
            1,kernel.pdf,isi_spike_counts,'valid')' / psthbin * 1e3;
        isi_n_trials = size(isi_spike_counts,1);
        isi_n_tbins = isi * psthbin;
        
        % T2-aligned, T1-split spike rates
        isi_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(isi_spike_flags) + ...
            t1(isi_spike_flags);
        isi_alignment_flags = ...
            valid_time >= isi_alignment_onset & ...
            valid_time < isi_alignment_onset + isi;
        isi_chunk_flags = isi_alignment_flags;
        isi_spkrates = isi_spike_rates;
        isi_spkrates(~isi_alignment_flags') = nan;
        isi_spkrates = reshape(...
            isi_spkrates(isi_chunk_flags'),[isi_n_tbins,isi_n_trials])';
        
        % compute mean spike density function
        time2plot = psthbin : psthbin : isi;
        time_flags = time2plot <= isi;
        isi_mu = nanmean(isi_spkrates(:,time_flags),1);
        isi_std = nanstd(isi_spkrates(:,time_flags),0,1);
        isi_trials_throughtime = sum(~isnan(isi_spkrates),1);
        isi_sem = isi_std ./ sqrt(isi_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(isi_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        isi_xpatch = [flagged_time,fliplr(flagged_time)];
        isi_ypatch = [isi_mu(~nan_flags)-isi_sem(~nan_flags),...
            fliplr(isi_mu(~nan_flags)+isi_sem(~nan_flags))];
        patch_alpha = [isi_trials_throughtime(~nan_flags),...
            fliplr(isi_trials_throughtime(~nan_flags))].^0;
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(2),isi_xpatch,isi_ypatch,t1_clrs(tt,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        isi_xpatch = flagged_time(~nan_flags);
        isi_ypatch = isi_mu(~nan_flags);
        isi_ypatch(end) = nan;
        patch_alpha = isi_trials_throughtime(~nan_flags).^0;
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(2),isi_xpatch,isi_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',t1_clrs(tt,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(2),time2plot(onset_flags),isi_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',t1_clrs(tt,:));
        
        % plot T1 raster
        isi_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(isi_spike_flags) + ...
            t1(isi_spike_flags));
        isi_trial_idcs = (1 : isi_n_trials)' + isi_n_trial_counter;
        isi_trial_mat = repmat(isi_trial_idcs,1,n_paddedtimebins);
        isi_spike_trials = isi_trial_mat(isi_spike_counts >= 1);
        isi_spike_times = isi_time_mat(isi_spike_counts >= 1);
        trial_sorter = [t1(isi_spike_flags),prev_choices(isi_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + isi_n_trial_counter;
        isi_sorted_trials = resorted_idcs(isi_spike_trials - isi_n_trial_counter);
        plot(sps(2+n_cols),isi_spike_times,isi_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',spike_markersize,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = [0,1,1,0] .* 50;
        ypatch = [.5,.5,isi_n_trials+.5,isi_n_trials+.5] + isi_n_trial_counter;
        patch(sps(2+n_cols),xpatch,ypatch,t1_clrs(tt,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        isi_n_trial_counter = isi_n_trial_counter + isi_n_trials;
        isi_boundaries(tt) = isi_n_trials;
    end
    
    % iterate through intensities
    for ii = 1 : n_i
        i2_flags = i2 == i_set(ii);
        s2_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            i2_flags;
        if sum(i1_spike_flags) == 0 || ...
                sum(s2_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        s2_spike_counts = data.FR(s2_spike_flags,:);
        s2_spike_rates = conv2(...
            1,kernel.pdf,s2_spike_counts,'valid')' / psthbin * 1e3;
        s2_n_trials = size(s2_spike_counts,1);
        s2_n_tbins = n_tbins + range(ti_padd) * psthbin;
        
        % T2-aligned, I2-split spike rates
        s2_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(s2_spike_flags) + ...
            t1(s2_spike_flags) + ...
            isi;
        s2_alignment_flags = ...
            valid_time >= s2_alignment_onset + ti_padd(1) & ...
            valid_time < s2_alignment_onset + t2(s2_spike_flags);
        s2_chunk_flags = ...
            valid_time >= s2_alignment_onset + ti_padd(1) & ...
            valid_time < s2_alignment_onset + max(t_set) + ti_padd(2);
        s2_spkrates = s2_spike_rates;
        s2_spkrates(~s2_alignment_flags') = nan;
        s2_spkrates = reshape(...
            s2_spkrates(s2_chunk_flags'),[s2_n_tbins,s2_n_trials])';
        
        % compute mean spike density function
        time2plot = ti_padd(1) + psthbin : psthbin : max(t_set) + ti_padd(2);
        time_flags = time2plot <= max(t_set) + ti_padd(2);
        s2_mu = nanmean(s2_spkrates(:,time_flags),1);
        s2_std = nanstd(s2_spkrates(:,time_flags),0,1);
        s2_trials_throughtime = sum(~isnan(s2_spkrates),1);
        s2_sem = s2_std ./ sqrt(s2_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(s2_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        s2_xpatch = [flagged_time,fliplr(flagged_time)];
        s2_ypatch = [s2_mu(~nan_flags)-s2_sem(~nan_flags),...
            fliplr(s2_mu(~nan_flags)+s2_sem(~nan_flags))];
        patch_alpha = [s2_trials_throughtime(~nan_flags),...
            fliplr(s2_trials_throughtime(~nan_flags))];
        patch_alpha = (patch_alpha - min(s2_trials_throughtime)) / ...
            range(s2_trials_throughtime);
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(3),s2_xpatch,s2_ypatch,i2_clrs(ii,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        s2_xpatch = flagged_time(~nan_flags);
        s2_ypatch = s2_mu(~nan_flags);
        s2_ypatch(end) = nan;
        patch_alpha = s2_trials_throughtime(~nan_flags);
        patch_alpha = (patch_alpha - min(s2_trials_throughtime)) / ...
            range(s2_trials_throughtime);
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(3),s2_xpatch,s2_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',i2_clrs(ii,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(3),time2plot(onset_flags),s2_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',i2_clrs(ii,:));
        
        % plot I2 raster
        s2_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(s2_spike_flags) + ...
            t1(s2_spike_flags) + ...
            isi);
        s2_trial_idcs = (1 : s2_n_trials)' + s2_n_trial_counter;
        s2_trial_mat = repmat(s2_trial_idcs,1,n_paddedtimebins);
        s2_spike_trials = s2_trial_mat(s2_spike_counts >= 1);
        s2_spike_times = s2_time_mat(s2_spike_counts >= 1);
        trial_sorter = [t2(s2_spike_flags),choice(s2_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + s2_n_trial_counter;
        s2_sorted_trials = resorted_idcs(s2_spike_trials - s2_n_trial_counter);
        plot(sps(3+n_cols),s2_spike_times,s2_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',spike_markersize,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = ti_padd(1) + [0,1,1,0] .* 50;
        ypatch = [.5,.5,s2_n_trials+.5,s2_n_trials+.5] + s2_n_trial_counter;
        patch(sps(3+n_cols),xpatch,ypatch,i2_clrs(ii,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        s2_n_trial_counter = s2_n_trial_counter + s2_n_trials;
        s2_boundaries(ii) = s2_n_trials;
    end
    
    % iterate through durations
    for tt = 1 : n_t
        t2_flags = t2 == t_set(tt);
        t2_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            t2_flags;
        if sum(t2_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        t2_spike_counts = data.FR(t2_spike_flags,:);
        t2_spike_rates = conv2(...
            1,kernel.pdf,t2_spike_counts,'valid')' / psthbin * 1e3;
        t2_n_trials = size(t2_spike_counts,1);
        t2_n_tbins = post_s2_delay * psthbin;
        
        % T2-aligned, T1-split spike rates
        t2_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(t2_spike_flags) + ...
            t1(t2_spike_flags) + ...
            isi + ...
            t2(t2_spike_flags);
        t2_alignment_flags = ...
            valid_time >= t2_alignment_onset & ...
            valid_time < t2_alignment_onset + post_s2_delay;
        t2_chunk_flags = t2_alignment_flags;
        t2_spkrates = t2_spike_rates;
        t2_spkrates(~t2_alignment_flags') = nan;
        t2_spkrates = reshape(...
            t2_spkrates(t2_chunk_flags'),[t2_n_tbins,t2_n_trials])';
        
        % compute mean spike density function
        time2plot = psthbin : psthbin : post_s2_delay;
        time_flags = time2plot <= post_s2_delay;
        t2_mu = nanmean(t2_spkrates(:,time_flags),1);
        t2_std = nanstd(t2_spkrates(:,time_flags),0,1);
        t2_trials_throughtime = sum(~isnan(t2_spkrates),1);
        t2_sem = t2_std ./ sqrt(t2_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(t2_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        t2_xpatch = [flagged_time,fliplr(flagged_time)];
        t2_ypatch = [t2_mu(~nan_flags)-t2_sem(~nan_flags),...
            fliplr(t2_mu(~nan_flags)+t2_sem(~nan_flags))];
        patch_alpha = [t2_trials_throughtime(~nan_flags),...
            fliplr(t2_trials_throughtime(~nan_flags))].^0;
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(4),t2_xpatch,t2_ypatch,t2_clrs(tt,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        t2_xpatch = flagged_time(~nan_flags);
        t2_ypatch = t2_mu(~nan_flags);
        t2_ypatch(end) = nan;
        patch_alpha = t2_trials_throughtime(~nan_flags).^0;
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(4),t2_xpatch,t2_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',t2_clrs(tt,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(4),time2plot(onset_flags),t2_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',t2_clrs(tt,:));
        
        % plot T1 raster
        t2_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(t2_spike_flags) + ...
            t1(t2_spike_flags) + ...
            isi + ...
            t2(t2_spike_flags));
        t2_trial_idcs = (1 : t2_n_trials)' + t2_n_trial_counter;
        t2_trial_mat = repmat(t2_trial_idcs,1,n_paddedtimebins);
        t2_spike_trials = t2_trial_mat(t2_spike_counts >= 1);
        t2_spike_times = t2_time_mat(t2_spike_counts >= 1);
        trial_sorter = [t1(t2_spike_flags),prev_choices(t2_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + t2_n_trial_counter;
        t2_sorted_trials = resorted_idcs(t2_spike_trials - t2_n_trial_counter);
        plot(sps(4+n_cols),t2_spike_times,t2_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',2,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = [0,1,1,0] .* 50;
        ypatch = [.5,.5,t2_n_trials+.5,t2_n_trials+.5] + t2_n_trial_counter;
        patch(sps(4+n_cols),xpatch,ypatch,t2_clrs(tt,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        t2_n_trial_counter = t2_n_trial_counter + t2_n_trials;
        t2_boundaries(tt) = t2_n_trials;
    end
    
    % check if all conditions have trials
    if all(isnan(s1_boundaries)) || ...
            all(isnan(t2_boundaries)) || ...
            all(isnan(i2_boundaries)) || ...
            all(isnan(t2_boundaries))
        continue;
    end
    
    % axes updates
    set(sps(1+n_cols),...
        'ylim',[1,nansum(s1_boundaries)]+[-1,1]*.5,...
        'ytick',unique([1;cumsum(s1_boundaries,'omitnan')]));
    set(sps(2+n_cols),...
        'ylim',[1,nansum(isi_boundaries)]+[-1,1]*.5,...
        'ytick',unique([1;cumsum(isi_boundaries,'omitnan')]));
    set(sps(3+n_cols),...
        'ylim',[1,nansum(s2_boundaries)]+[-1,1]*.5,...
        'ytick',unique([1;cumsum(s2_boundaries,'omitnan')]));
    set(sps(4+n_cols),...
        'ylim',[1,nansum(t2_boundaries)]+[-1,1]*.5,...
        'ytick',unique([1;cumsum(t2_boundaries,'omitnan')]));
    
    
    % axes linkage
    linkaxes(sps(1:n_cols),'y');
    
    % update y-axis limits
    yylim = [min([ylim(sps(1)),ylim(sps(2)),ylim(sps(3))]),...
        max([ylim(sps(1)),ylim(sps(2)),ylim(sps(3))])];
    yylim = 5 * [floor(yylim(1)/5),floor(yylim(2)/5)];
    if ismember(neurons2plot(nn),[215,462])
        yylim = [0,60];
    elseif ismember(neurons2plot(nn),[402])
        yylim = [0,50];
    elseif ismember(neurons2plot(nn),[526])
        yylim = [0,40];
    end
    yylim = max(yylim,[0,1]);
    set(sps(1:n_cols),...
        'ylim',yylim,...
        'ytick',yylim,...
        'clipping','off');
    
    % save figure
    if want2save
        try
            % save settings
            png_file = fullfile(raster_path,[get(fig,'name'),'.png']);
            print(fig,png_file,'-dpng','-r300','-painters');
            svg_file = fullfile(panel_path,[fig.Name,'.svg']);
            print(fig,svg_file,'-dsvg','-painters');
            close(fig);
        catch
            close(fig);
        end
    else
        pause(1);
        close(fig);
    end
end
