%% initialization
if ~exist('data','var')
    toso2021_wrapper;
end

%% choice GLM (complete model)
X = [prev_t1,prev_t2,prev_i1,prev_i2,s1,s2,d1,d2];
Z = (X - nanmean(X)) ./ nanstd(X);
% mdl = stepwiseglm(Z(valid_flags,:),choice(valid_flags,:),'linear',...
%     ...'constant','upper','interactions',...
%     'criterion','bic',...
%     'predictorvars',{'T1_{t-1}','T2_{t-1}','I1_{t-1}','I2_{t-1}',...
%     s1_lbl,s2_lbl,d1_lbl,d2_lbl},...
%     'distribution','binomial',...
%     'intercept',true);
mdl = fitglm(Z(valid_flags,:),choice(valid_flags,:),'interactions',...
    'predictorvars',{'T1_{t-1}','T2_{t-1}','I1_{t-1}','I2_{t-1}',...
    s1_lbl,s2_lbl,d1_lbl,d2_lbl},...
    'distribution','binomial',...
    'intercept',true);
betas = mdl.Coefficients.Estimate;
% [B,mdlinfo] = lassoglm(...
%     Z(valid_flags,:),choice(valid_flags,:),'binomial',...
%     'standardize',true,...
%     'lambda',1e-1,...
%     'alpha',1e-2,...
%     'CV',10);
% betas = [mdlinfo.Intercept(mdlinfo.IndexMinDeviance);...
%     B(:,mdlinfo.IndexMinDeviance)];
beta_s1 = betas(2);
beta_s2 = betas(3);
n_betas = numel(betas);
beta_labels = mdl.CoefficientNames;
beta_labels{1} = 'Intercept';
fig = figure(figopt,...
    'name','choice_GLM_interactions');
axes(axesopt.default,...
    'xlim',[0,n_betas+1],...
    'xtick',1:n_betas,...
    'xticklabelrotation',45,...
    'xticklabel',beta_labels,...
    'plotboxaspectratio',[3,1,1]);
title(sprintf('%s > %s ~ Binomial(\\phi(\\betaX))',s2_lbl,s1_lbl));
xlabel('X');
ylabel('\beta');

% plot coefficients
p = stem(1:numel(betas),betas,...
    'color','k',...
    'marker','o',...
    'markersize',10,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'linewidth',1.5);
p.BaseLine.LineWidth = p.LineWidth;

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end