%% initialization
if ~exist('data','var')
    toso2021_wrapper;
end

%% choice GLM (partial model)
mdl = fitglm([d1(valid_flags),d2(valid_flags)].*[1,1],...
    choice(valid_flags,:),'linear',...
    'predictorvars',{d1_lbl,d2_lbl},...
    'distribution','binomial',...
    'intercept',true);
betas = mdl.Coefficients.Estimate;
beta_0 = betas(1);
beta_d1 = betas(2);
beta_d2 = betas(3);

%% color limits specification

% color limits
clims = [0,1] + [+1,-1] * .3;

%% sampling scheme w/ D1-D2 pairwise performance

% transfer function
tfun = @(x) log(x);
invfun = @(x) exp(x);

% pair specification
d_pairs = [d1,d2];
d_pairset = unique(d_pairs(valid_flags,:),'rows');
n_pairs = size(d_pairset,1);

% preallocation
p_choice = nan(n_pairs,1);

% iterate through D1-D2 pairs
for ii = 1 : n_pairs
    s_flags = all(d_pairs == d_pairset(ii,:),2);
    trial_flags = ...
        valid_flags & ...
        unique_flags & ...
        s_flags;
    if sum(trial_flags) == 0
        continue;
    end
    
    % compute average performance for the current pair
    p_choice(ii) = mean(choice(trial_flags));
end

% nan filtering
d_pairset = d_pairset(~isnan(p_choice),:);
p_choice = p_choice(~isnan(p_choice));

% figure & axes initialization
fig = figure(figopt,...
    'name','generalization_matrix_Di');
axes(axesopt.default,...
    'xlim',tfun([d_set(1),d_set(end)]) + [-1,1] * .1 * range(tfun(d_set)),...
    'ylim',tfun([d_set(1),d_set(end)]) + [-1,1] * .1 * range(tfun(d_set)),...
    'xtick',tfun(d_set),...
    'ytick',tfun(d_set),...
    'xticklabel',num2cell(d_set),...
    'yticklabel',num2cell(d_set),...
    'xticklabelrotation',45,...
    'yticklabelrotation',45,...
    'clim',clims,...
    'xscale','linear',...
    'yscale','linear');
xlabel(sprintf('%s (%s)',d1_lbl,d_units));
ylabel(sprintf('%s (%s)',d2_lbl,d_units));

% colorbar
cbar = colorbar(...
    'color','k',...
    'limits',clims,...
    'box',axesopt.default.box,...
    'linewidth',axesopt.default.linewidth,...
    'tickdirection','out',...
    'ticklength',unique(axesopt.default.ticklength),...
    'fontsize',axesopt.default.fontsize,...
    'ticks',unique([clims,.5]));
cbar.Label.String = sprintf('P(%s > %s)',s2_lbl,s1_lbl);
cbar.Label.Rotation = -90;
cbar.Label.VerticalAlignment = 'bottom';

% plot reference lines
plot(xlim,ylim,':k',...
    'linewidth',1);
plot(tfun([1,1]*median(d1(valid_flags))),ylim,':k',...
    'linewidth',1);
plot(xlim,tfun([1,1]*median(d2(valid_flags))),':k',...
    'linewidth',1);

% plot NDD lines
plot(tfun(d_set([1,end-1])),tfun(d_set([1+1,end])),':k',...
    'linewidth',1);
plot(tfun(d_set([1+1,end])),tfun(d_set([1,end-1])),':k',...
    'linewidth',1);

% plot decision boundary
x = linspace(min(d_pairs(:,1)),max(d_pairs(:,1)),1e3);
y = -beta_d1 / beta_d2 * x - beta_0 / beta_d2;
plot(tfun(x),tfun(y),'--k',...
    'linewidth',1.5);

% plot performance
scatter(...
    tfun(d_pairset(:,1)),...
    tfun(d_pairset(:,2)),...
    250,p_choice,'s','filled',...
    'markeredgecolor','k',...
    'linewidth',1.5);

% iterate through pairs
for ii = 1 : n_pairs
    if d_pairset(ii,2) > d_pairset(ii,1)
        vertical_gain = .92;
    else
        vertical_gain = 1.095;
    end
    
    % annotate performance
    text(tfun(d_pairset(ii,1) * 1.025),tfun(d_pairset(ii,2) * vertical_gain),...
        sprintf('%.0f%%',p_choice(ii)*100),...
        'color','k',...
        'fontsize',axesopt.default.fontsize,...
        'horizontalalignment','center',...
        'verticalalignment','middle');
end

% annotate NDD = 0
text(.95,.95,'NID = 0',...
    'units','normalized',...
    'color','k',...
    'rotation',45,...
    'fontsize',axesopt.default.fontsize,...
    'horizontalalignment','right',...
    'verticalalignment','bottom');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% contraction bias visualization

% figure & axes initialization
fig = figure(figopt,...
    'name','contraction_bias_Di');
ax = axes(axesopt.default,...
    'xlim',tfun([d_set(1),d_set(end)]) + [-1,1] * .1 * range(tfun(d_set)),...
    'ylim',tfun([d_set(1),d_set(end)]) + [-1,1] * .1 * range(tfun(d_set)),...
    'xtick',tfun(d_set),...
    'ytick',tfun(d_set),...
    'xticklabel',num2cell(d_set),...
    'yticklabel',num2cell(d_set),...
    'xticklabelrotation',45,...
    'yticklabelrotation',45,...
    'clim',clims,...
    'xscale','linear',...
    'yscale','linear');
xlabel(sprintf('%s (%s)',d1_lbl,d_units));
ylabel(sprintf('%s (%s)',d2_lbl,d_units));

% colorbar
cbar = colorbar(...
    'color','k',...
    'limits',clims,...
    'box',axesopt.default.box,...
    'linewidth',axesopt.default.linewidth,...
    'yaxislocation','right',...
    'location','eastoutside',...
    'tickdirection','out',...
    'ticklength',unique(axesopt.default.ticklength),...
    'fontsize',axesopt.default.fontsize,...
    'ticks',unique([clims,.5]));
cbar.Label.String = sprintf('P(%s > %s)',s2_lbl,s1_lbl);
cbar.Label.Rotation = -90;
cbar.Label.VerticalAlignment = 'bottom';

% plot hypothesized probability of reporting S2 > S1
si_x = linspace(invfun(min(xlim)),invfun(max(xlim)),1e2);
beta = 1.75;
p_choice_mat = 1 ./ (1 + exp(-beta * (si_x' - si_x) ./ (si_x' + si_x)));
h = pcolor(tfun(si_x),tfun(si_x),p_choice_mat);
h.EdgeColor = 'none';
h.FaceColor = 'interp';

% plot reference lines
plot(xlim,ylim,':k',...
    'linewidth',1.5);

% compute <S1>
d1_avg = nanmedian(d1(valid_flags));

% plot expected value of the d1 prior distribution
plot(tfun([1,1]*d1_avg),ylim,':k',...
    'linewidth',1.5);

% plot performance
scatter(...
    tfun(d_pairset(:,1)),...
    tfun(d_pairset(:,2)),...
    250,p_choice,'s','filled',...
    'markeredgecolor','k',...
    'linewidth',1.5);

% iterate through pairs
for ii = 1 : n_pairs
    if d_pairset(ii,2) > d_pairset(ii,1)
        vertical_gain = .92;
        font_clr = 'k';
    else
        vertical_gain = 1.095;
        font_clr = 'w';
    end
    
    % annotate performance
    text(tfun(d_pairset(ii,1) * 1.025),tfun(d_pairset(ii,2) * vertical_gain),...
        sprintf('%.0f%%',p_choice(ii)*100),...
        'fontsize',axesopt.default.fontsize,...
        'color',font_clr,...
        'horizontalalignment','center',...
        'verticalalignment','middle');
end

% graphical object preallocation
p = gobjects(n_pairs,1);

% iterate through pairs
for ii = 1 : n_pairs
    
    % compute post-contraction percept
    s_dv = (d_pairset(ii,2) - si_x) ./ (d_pairset(ii,2) + si_x);
    p_choice_hypo = 1 ./ (1 + exp(-beta * s_dv));
    [~,idx] = min(abs(p_choice(ii) - p_choice_hypo));
    
    % plot post-contraction percept
    xpatch = linspace(d_pairset(ii,1),si_x(idx),1e3);
    ypatch = [repmat(d_pairset(ii,2),1,1e3-1),nan];
    cpatch = repmat(p_choice(ii),1,1e3);
    p(ii) = plot(tfun([d_pairset(ii,1),si_x(idx)]),[1,1]*tfun(d_pairset(ii,2)),...
        'color','k',...
        'linewidth',4.5);
    patch(tfun(xpatch),tfun(ypatch),ypatch,cpatch,...
        'edgecolor','interp',...
        'linewidth',1.5);
    scatter(tfun(si_x(idx)),tfun(d_pairset(ii,2)),...
        75,p_choice(ii),'o','filled',...
        'markeredgecolor','k',...
        'linewidth',1.5);
end

% annotate expected value of d1
text(tfun(d1_avg),max(ylim),...
    sprintf('<%s>',d1_lbl),...
    'fontsize',axesopt.default.fontsize,...
    'horizontalalignment','center',...
    'verticalalignment','bottom');

% annotate NDD = 0
text(.95,.95,'NID = 0',...
    'units','normalized',...
    'color','k',...
    'rotation',45,...
    'fontsize',axesopt.default.fontsize,...
    'horizontalalignment','right',...
    'verticalalignment','bottom');

% ui restacking
uistack(p,'bottom');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end