%% initialization
if ~exist('data','var')
    toso2021_wrapper;
end

%% ROI settings

% Si-aligned ROI
pre_padd = 500 * 0;
roi2use = [-pre_padd*0,t_set(end)];
roi2plot = [-pre_padd,t_set(end)];
roi2plot_padded = roi2plot + [-1,1] * .0 * range(roi2plot);
roi2use_n_bins = range(roi2use) / psthbin;
roi2plot_n_bins = range(roi2plot_padded) / psthbin;
roi2use_time = linspace(roi2use(1),roi2use(2),roi2use_n_bins);
roi2plot_time = linspace(roi2plot_padded(1),roi2plot_padded(2),roi2plot_n_bins);
roi2use_flags = ...
    roi2plot_time >= roi2use(1) & ...
    roi2plot_time <= roi2use(2);

% ISI-aligned ROI settings
isi_n_bins = isi / psthbin;
isi_time = linspace(0,isi,isi_n_bins);

%% cross-validation settings
n_xval_runs = 1; % 100

%% PCA settings
n_pcs2keep = 3;

%% construct Si-aligned psths

% preallocation
s1_psths = nan(roi2plot_n_bins,n_neurons);
isi_psths = nan(isi_n_bins,n_neurons);
s2_psths = nan(roi2plot_n_bins,n_neurons);

% iterate through neurons
for nn = 1 : n_neurons
    progressreport(nn,n_neurons,'parsing neural data');
    neuron_flags = data.NeuronNumb == flagged_neurons(nn);
    s1_spike_flags = ...
        valid_flags & ...
        neuron_flags;
    isi_spike_flags = ...
        valid_flags & ...
        neuron_flags;
    s2_spike_flags = ...
        valid_flags & ...
        neuron_flags;
    
    % fetch S1-aligned spike counts & compute spike rates
    s1_spike_rates = data.SDF(s1_spike_flags,:);
    s1_n_trials = size(s1_spike_rates,1);
    
    % fetch ISI-aligned spike counts & compute spike rates
    isi_spike_rates = data.SDF(isi_spike_flags,:);
    isi_n_trials = size(isi_spike_rates,1);
    
    % fetch S2-aligned spike counts & compute spike rates
    s2_spike_rates = data.SDF(s2_spike_flags,:);
    s2_n_trials = size(s2_spike_rates,1);
    
    % S1-aligned spike rates
    s1_alignment_offset = ...
        pre_init_padding + ...
        pre_s1_delay(s1_spike_flags);
    s1_alignment_flags = ...
        padded_time >= s1_alignment_offset + roi2plot_padded(1) & ...
        padded_time < s1_alignment_offset + t1(s1_spike_flags);
    s1_chunk_flags = ...
        padded_time >= s1_alignment_offset + roi2plot_padded(1) & ...
        padded_time < s1_alignment_offset + roi2plot_padded(2);
    s1_spkrates = s1_spike_rates';
    s1_spkrates(~s1_alignment_flags') = nan;
    s1_spkrates = reshape(...
        s1_spkrates(s1_chunk_flags'),...
        [roi2plot_n_bins,s1_n_trials])';
    
    % ISI-aligned spike rates
    isi_alignment = ...
        pre_init_padding + ...
        pre_s1_delay(isi_spike_flags) + ...
        t1(isi_spike_flags);
    isi_alignment_flags = ...
        padded_time >= isi_alignment & ...
        padded_time < isi_alignment + isi;
    isi_chunk_flags = isi_alignment_flags;
    isi_spkrates = isi_spike_rates';
    isi_spkrates(~isi_alignment_flags') = nan;
    isi_spkrates = reshape(...
        isi_spkrates(isi_chunk_flags'),...
        [isi_n_bins,isi_n_trials])';
    
    % S2-aligned spike rates
    s2_alignment = ...
        pre_init_padding + ...
        pre_s1_delay(s2_spike_flags) + ...
        t1(s2_spike_flags) + ...
        isi;
    s2_alignment_flags = ...
        padded_time >= s2_alignment + roi2plot_padded(1) & ...
        padded_time < s2_alignment + t2(s2_spike_flags);
    s2_chunk_flags = ...
        padded_time >= s2_alignment + roi2plot_padded(1) & ...
        padded_time < s2_alignment + roi2plot_padded(2);
    s2_spkrates = s2_spike_rates';
    s2_spkrates(~s2_alignment_flags') = nan;
    s2_spkrates = reshape(...
        s2_spkrates(s2_chunk_flags'),...
        [roi2plot_n_bins,s2_n_trials])';
    
    % compute mean spike density functions
    s1_psths(:,nn) = nanmean(s1_spkrates);
    isi_psths(:,nn) = nanmean(isi_spkrates);
    s2_psths(:,nn) = nanmean(s2_spkrates);
end

%% normalization

% compute neuron-wise cross-epoch statistics
mus = nanmean([s1_psths; isi_psths; s2_psths]);
sigs = nanstd([s1_psths; isi_psths; s2_psths]);

% z-score S1-aligned spike density functions
s1_mus = mus; % nanmean(s1_psths(roi2use_flags,:,:),[1,3]);
s1_sigs = sigs; % nanstd(s1_psths(roi2use_flags,:,:),0,[1,3]);
s1_zpsths = (s1_psths - s1_mus) ./ s1_sigs;

% z-score ISI-aligned spike density functions
isi_mus = mus; % nanmean(isi_psths,[1,3]);
isi_sigs = sigs; % nanstd(isi_psths,0,[1,3]);
isi_zpsths = (isi_psths - isi_mus) ./ isi_sigs;

% z-score S2-aligned spike density functions
s2_mus = mus; % nanmean(s2_psths(roi2use_flags,:,:),[1,3]);
s2_sigs = sigs; % nanstd(s2_psths(roi2use_flags,:,:),0,[1,3]);
s2_zpsths = (s2_psths - s2_mus) ./ s2_sigs;

%% compute alignment-specific weights

% compute S1-aligned weights
time_mat = repmat(roi2use(1) + psthbin : psthbin : roi2use(2),n_total_trials,1);
s1_weights = sum(time_mat(valid_flags,:) <= t1(valid_flags));
s1_weights = s1_weights / sum(s1_weights);

% compute ISI-aligned weights
isi_weights = ones(1,isi_n_bins) / isi_n_bins;

% compute S2-aligned weights
time_mat = repmat(roi2use(1) + psthbin : psthbin : roi2use(2),n_total_trials,1);
s2_weights = sum(time_mat(valid_flags,:) <= t2(valid_flags));
s2_weights = s2_weights / sum(s2_weights);

%% PCA

% compute S1-aligned PCs
s1_coeff = pca(s1_zpsths(roi2use_flags,:),...
    'weights',s1_weights);

% compute S2-aligned PCs
isi_coeff = pca(isi_zpsths,...
    'weights',isi_weights);

% compute S2-aligned PCs
s2_coeff = pca(s2_zpsths(roi2use_flags,:),...
    'weights',s2_weights);

% project epochs onto S1-aligned PCs
s1_s1_score = s1_zpsths * s1_coeff;
s1_isi_score = isi_zpsths * s1_coeff;
s1_s2_score = s2_zpsths * s1_coeff;

% project epochs onto ISI-aligned PCs
isi_s1_score = s1_zpsths * isi_coeff;
isi_isi_score = isi_zpsths * isi_coeff;
isi_s2_score = s2_zpsths * isi_coeff;

% project epochs onto S2-aligned PCs
s2_s1_score = s1_zpsths * s2_coeff;
s2_isi_score = isi_zpsths * s2_coeff;
s2_s2_score = s2_zpsths * s2_coeff;

%% cross-validation

% preallocation
s1_s1_exp = nan(n_neurons,n_xval_runs);
s1_isi_exp = nan(n_neurons,n_xval_runs);
s1_s2_exp = nan(n_neurons,n_xval_runs);
isi_s1_exp = nan(n_neurons,n_xval_runs);
isi_isi_exp = nan(n_neurons,n_xval_runs);
isi_s2_exp = nan(n_neurons,n_xval_runs);
s2_s1_exp = nan(n_neurons,n_xval_runs);
s2_isi_exp = nan(n_neurons,n_xval_runs);
s2_s2_exp = nan(n_neurons,n_xval_runs);

% iterate through cross-validation runs
for rr = 1 : n_xval_runs
    progressreport(rr,n_xval_runs,'cross-validating explained variance');
    
    % preallocation
    s1_psths_xval = nan(roi2plot_n_bins,n_neurons,2);
    isi_psths_xval = nan(isi_n_bins,n_neurons,2);
    s2_psths_xval = nan(roi2plot_n_bins,n_neurons,2);
    
    % iterate through neurons
    for nn = 1 : n_neurons
        neuron_flags = data.NeuronNumb == flagged_neurons(nn);
        s1_spike_flags = ...
            valid_flags & ...
            neuron_flags;
        isi_spike_flags = ...
            valid_flags & ...
            neuron_flags;
        s2_spike_flags = ...
            valid_flags & ...
            neuron_flags;
        
        % fetch S1-aligned spike counts & compute spike rates
        s1_spike_rates = data.SDF(s1_spike_flags,:);
        s1_n_trials = size(s1_spike_rates,1);
        s1_idcs = 1 : s1_n_trials;
        
        % fetch ISI-aligned spike counts & compute spike rates
        isi_spike_rates = data.SDF(isi_spike_flags,:);
        isi_n_trials = size(isi_spike_rates,1);
        isi_idcs = 1 : isi_n_trials;
        
        % fetch S2-aligned spike counts & compute spike rates
        s2_spike_rates = data.SDF(s2_spike_flags,:);
        s2_n_trials = size(s2_spike_rates,1);
        s2_idcs = 1 : s2_n_trials;
        
        % S1-aligned spike rates
        s1_alignment_offset = ...
            pre_init_padding + ...
            pre_s1_delay(s1_spike_flags);
        s1_alignment_flags = ...
            padded_time >= s1_alignment_offset + roi2plot_padded(1) & ...
            padded_time < s1_alignment_offset + t1(s1_spike_flags);
        s1_chunk_flags = ...
            padded_time >= s1_alignment_offset + roi2plot_padded(1) & ...
            padded_time < s1_alignment_offset + roi2plot_padded(2);
        s1_spkrates = s1_spike_rates';
        s1_spkrates(~s1_alignment_flags') = nan;
        s1_spkrates = reshape(...
            s1_spkrates(s1_chunk_flags'),...
            [roi2plot_n_bins,s1_n_trials])';
        
        % ISI-aligned spike rates
        isi_alignment = ...
            pre_init_padding + ...
            pre_s1_delay(isi_spike_flags) + ...
            t1(isi_spike_flags);
        isi_alignment_flags = ...
            padded_time >= isi_alignment & ...
            padded_time < isi_alignment + isi;
        isi_chunk_flags = isi_alignment_flags;
        isi_spkrates = isi_spike_rates';
        isi_spkrates(~isi_alignment_flags') = nan;
        isi_spkrates = reshape(...
            isi_spkrates(isi_chunk_flags'),...
            [isi_n_bins,isi_n_trials])';
        
        % S2-aligned spike rates
        s2_alignment = ...
            pre_init_padding + ...
            pre_s1_delay(s2_spike_flags) + ...
            t1(s2_spike_flags) + ...
            isi;
        s2_alignment_flags = ...
            padded_time >= s2_alignment + roi2plot_padded(1) & ...
            padded_time < s2_alignment + t2(s2_spike_flags);
        s2_chunk_flags = ...
            padded_time >= s2_alignment + roi2plot_padded(1) & ...
            padded_time < s2_alignment + roi2plot_padded(2);
        s2_spkrates = s2_spike_rates';
        s2_spkrates(~s2_alignment_flags') = nan;
        s2_spkrates = reshape(...
            s2_spkrates(s2_chunk_flags'),...
            [roi2plot_n_bins,s2_n_trials])';
        
        % cross-validation
        s1_idcs_k1 = sort(randperm(s1_n_trials,round(s1_n_trials/2)));
        s1_idcs_k2 = s1_idcs(~ismember(s1_idcs,s1_idcs_k1));
        isi_idcs_k1 = sort(randperm(isi_n_trials,round(isi_n_trials/2)));
        isi_idcs_k2 = isi_idcs(~ismember(isi_idcs,isi_idcs_k1));
        s2_idcs_k1 = sort(randperm(s2_n_trials,round(s2_n_trials/2)));
        s2_idcs_k2 = s2_idcs(~ismember(s2_idcs,s2_idcs_k1));
        
        % compute mean spike density functions
        s1_psths_xval(:,nn,1) = nanmean(s1_spkrates(s1_idcs_k1,:),1);
        s1_psths_xval(:,nn,2) = nanmean(s1_spkrates(s1_idcs_k2,:),1);
        isi_psths_xval(:,nn,1) = nanmean(isi_spkrates(isi_idcs_k1,:),1);
        isi_psths_xval(:,nn,2) = nanmean(isi_spkrates(isi_idcs_k2,:),1);
        s2_psths_xval(:,nn,1) = nanmean(s2_spkrates(s2_idcs_k1,:),1);
        s2_psths_xval(:,nn,2) = nanmean(s2_spkrates(s2_idcs_k2,:),1);
    end
    
    %% normalization
    
    % z-score S1-aligned spike density functions
    s1_mus = mus; % nanmean(s1_psths(roi2use_flags,:,:),[1,3]);
    s1_sigs = sigs; % nanstd(s1_psths(roi2use_flags,:,:),0,[1,3]);
    s1_zpsths_xval = (s1_psths_xval - s1_mus) ./ s1_sigs;
    
    % z-score ISI-aligned spike density functions
    isi_mus = mus; % nanmean(isi_psths,[1,3]);
    isi_sigs = sigs; % nanstd(isi_psths,0,[1,3]);
    isi_zpsths_xval = (isi_psths_xval - isi_mus) ./ isi_sigs;
    
    % z-score S2-aligned spike density functions
    s2_mus = mus; % nanmean(s2_psths(roi2use_flags,:,:),[1,3]);
    s2_sigs = sigs; % nanstd(s2_psths(roi2use_flags,:,:),0,[1,3]);
    s2_zpsths_xval = (s2_psths_xval - s2_mus) ./ s2_sigs;
    
    %% PCA
    
    % compute S1-aligned PCs
    s1_coeff_xval = pca(s1_zpsths_xval(roi2use_flags,:,1),...
        'weights',s1_weights);
    
    % compute S2-aligned PCs
    isi_coeff_xval = pca(isi_zpsths_xval(:,:,1),...
        'weights',isi_weights);
    
    % compute_xval S2-aligned PCs
    s2_coeff_xval = pca(s2_zpsths_xval(roi2use_flags,:,1),...
        'weights',s2_weights);
    
    % project epochs onto S1-aligned PCs
    s1_s1_score_xval = s1_zpsths_xval(:,:,2) * s1_coeff_xval;
    s1_isi_score_xval = isi_zpsths_xval(:,:,2) * s1_coeff_xval;
    s1_s2_score_xval = s2_zpsths_xval(:,:,2) * s1_coeff_xval;
    
    % project epochs onto ISI-aligned PCs
    isi_s1_score_xval = s1_zpsths_xval(:,:,2) * isi_coeff_xval;
    isi_isi_score_xval = isi_zpsths_xval(:,:,2) * isi_coeff_xval;
    isi_s2_score_xval = s2_zpsths_xval(:,:,2) * isi_coeff_xval;
    
    % project epochs onto S2-aligned PCs
    s2_s1_score_xval = s1_zpsths_xval(:,:,2) * s2_coeff_xval;
    s2_isi_score_xval = isi_zpsths_xval(:,:,2) * s2_coeff_xval;
    s2_s2_score_xval = s2_zpsths_xval(:,:,2) * s2_coeff_xval;
    
    %% compute explained variance
    
    % variance explained by S1-aligned PCs
    s1_s1_lat = nanvar(s1_s1_score_xval(roi2use_flags,:),s1_weights)';
    s1_s1_exp(:,rr) = s1_s1_lat ./ sum(s1_s1_lat) * 100;
    s1_isi_lat = nanvar(s1_isi_score_xval,isi_weights)';
    s1_isi_exp(:,rr) = s1_isi_lat ./ sum(s1_isi_lat) * 100;
    s1_s2_lat = nanvar(s1_s2_score_xval(roi2use_flags,:),s2_weights)';
    s1_s2_exp(:,rr) = s1_s2_lat ./ sum(s1_s2_lat) * 100;
    
    % variance explained by S2-aligned PCs
    isi_s1_lat = nanvar(isi_s1_score_xval(roi2use_flags,:),s1_weights)';
    isi_s1_exp(:,rr) = isi_s1_lat ./ sum(isi_s1_lat) * 100;
    isi_isi_lat = nanvar(isi_isi_score_xval,isi_weights)';
    isi_isi_exp(:,rr) = isi_isi_lat ./ sum(isi_isi_lat) * 100;
    isi_s2_lat = nanvar(isi_s2_score_xval(roi2use_flags,:),s2_weights)';
    isi_s2_exp(:,rr) = isi_s2_lat ./ sum(isi_s2_lat) * 100;
    
    % variance explained by S2-aligned PCs
    s2_s1_lat = nanvar(s2_s1_score_xval(roi2use_flags,:),s1_weights)';
    s2_s1_exp(:,rr) = s2_s1_lat ./ sum(s2_s1_lat) * 100;
    s2_isi_lat = nanvar(s2_isi_score_xval,isi_weights)';
    s2_isi_exp(:,rr) = s2_isi_lat ./ sum(s2_isi_lat) * 100;
    s2_s2_lat = nanvar(s2_s2_score_xval(roi2use_flags,:),s2_weights)';
    s2_s2_exp(:,rr) = s2_s2_lat ./ sum(s2_s2_lat) * 100;
end

%% cross-run statistics on variance explained
avgfun = @(x,d) nanmean(x,d);
errfun = @(x,d) nanstd(x,0,d);

% compute location statistic
s1_s1_exp_avg = avgfun(s1_s1_exp,2);
s1_isi_exp_avg = avgfun(s1_isi_exp,2);
s1_s2_exp_avg = avgfun(s1_s2_exp,2);
isi_s1_exp_avg = avgfun(isi_s1_exp,2);
isi_isi_exp_avg = avgfun(isi_isi_exp,2);
isi_s2_exp_avg = avgfun(isi_s2_exp,2);
s2_s1_exp_avg = avgfun(s2_s1_exp,2);
s2_isi_exp_avg = avgfun(s2_isi_exp,2);
s2_s2_exp_avg = avgfun(s2_s2_exp,2);

% compute dispersion statistic
s1_s1_exp_err = errfun(s1_s1_exp,2);
s1_isi_exp_err = errfun(s1_isi_exp,2);
s1_s2_exp_err = errfun(s1_s2_exp,2);
isi_s1_exp_err = errfun(isi_s1_exp,2);
isi_isi_exp_err = errfun(isi_isi_exp,2);
isi_s2_exp_err = errfun(isi_s2_exp,2);
s2_s1_exp_err = errfun(s2_s1_exp,2);
s2_isi_exp_err = errfun(s2_isi_exp,2);
s2_s2_exp_err = errfun(s2_s2_exp,2);

%%

figure(figopt,...
    'position',[1.8000 41.8000 1.0248e+03 1.0288e+03]);

for pc_s1 = 1 : 3
    [x,idcs] = sort(s1_coeff(:,pc_s1));
    for pc_s2 = 1 : 3
        sp_idx = pc_s2 + (pc_s1 - 1) * 3;
        subplot(3,3,sp_idx);
        hold on;
        xlabel(sprintf('S1-aligned PC_%i weights',pc_s1))
        ylabel(sprintf('S2-aligned PC_%i weights',pc_s2))
        y = s2_coeff(idcs,pc_s2);
        mdl = fitlm(x,y,...
            'intercept',false);
        if mdl.Coefficients.pValue(end) < .05
            linestyle = '-';
        else
            linestyle = '--';
        end
        plot(x,y,'.k')
        histogram2(x,y,7,...
            'displayStyle','tile',...
            'showemptybins','on',...
            'edgecolor','none');
        plot(x,mdl.predict(x(:)),'r',...
            'linestyle',linestyle,...
            'linewidth',1.5);
        axis tight;
        axis square;
    end
end

%%

% figure(figopt);
%
% for ii = 1 : 2
%     for jj = 1 : 2
%         sp_idx = jj + (ii -1) * 2;
%         subplot(2,2,sp_idx);
%         hold on;
%
%         % preallocation
%         corrcoeffs = nan(n_neurons,1);
%
%         % iterate through neurons
%         for nn = 1 : n_neurons
%
%             x = s1_zpsths(:,nn,ii);
%             y = s2_zpsths(:,nn,jj);
%             nan_flags = isnan(x) | isnan(y);
%             c = corrcoef(x(~nan_flags),y(~nan_flags));
%             corrcoeffs(nn) = c(2);
%         end
%
%         %
%         histogram(corrcoeffs,50);
%         plot([1,1]*mean(corrcoeffs),ylim,'-k');
%         xlabel('Correlation coefficients between S1- and S2-aligned psths')
%     end
% end

%% color settings
s1_clr = [1,1,1] * .75;
isi_clr = [0,.8,.8];
s2_clr = [0,0,0];

%% S1-aligned PC projections

% figure initialization
fig = figure(figopt,...
    'position',[35,130,966,860],...
    'name','pc_projections_s1');
sps = gobjects(n_pcs2keep,1);
for pc = 1 : n_pcs2keep
    sps(pc) = subplot(n_pcs2keep,1,pc);
    xlabel(sps(pc),'Time since S1 onset (ms)');
    ylabel(sps(pc),sprintf('S1-aligned PC %i',pc));
end
xxlim = t_set(end) * [-1,1] + [-1,0] * (isi + pre_padd) + isi + t_set(end);
xxtick = unique([[roi2plot';0;t_set];-isi;[roi2plot';0;t_set]-isi-t_set(end)]+isi+t_set(end));
xxticklabel = num2cell(xxtick);
xxticklabel(~ismember(xxtick,...
    [-isi-t_set(end)-pre_padd,-isi-t_set(end),-isi,-pre_padd,0,t_set(end)]+isi+t_set(end))) = {''};
set(sps,...
    axesopt.default,...
    'plotboxaspectratio',[4,1,1],...
    'ticklength',axesopt.default.ticklength * 1/2,...
    'xlim',xxlim + [-1,1] * .05 * 1/4 * range(xxlim),...
    'xtick',xxtick,...
    'xticklabel',xxticklabel,...
    'ylimspec','tight');

% link axes
linkaxes(sps,'x');

% iterate through pcs
for pc = 1 : n_pcs2keep
    
    % compute surviving trial counts (through time)
    time_mat = repmat(...
        roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
    surviving_trial_counts = sum(time_mat(valid_flags,:) <= t1(valid_flags));
    
    % patch projection
    mu_xpatch = roi2plot_time;
    mu_ypatch = s1_s1_score(:,pc)';
    mu_ypatch(end) = nan;
    mu_apatch = surviving_trial_counts;
    mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
        range(alphabounds_mu) + alphabounds_mu(1);
    if fadeifnoisy
        alpha_levels = unique(mu_apatch,'stable');
        n_alpha_levels = numel(alpha_levels);
        for aa = 1 : n_alpha_levels
            alpha_flags = mu_apatch == alpha_levels(aa);
            p = patch(sps(pc),...
                [mu_xpatch(alpha_flags),nan],...
                [mu_ypatch(alpha_flags),nan],0,...
                'edgealpha',alpha_levels(aa),...
                'edgecolor',s1_clr,...
                'facecolor','none',...
                'linewidth',1.5);
        end
    else
        p = plot(sps(pc),roi2plot_time,...
            s1_s1_score(:,pc),...
            'color',s1_clr,...
            'linestyle','-',...
            'linewidth',1.5);
    end
    
    % plot projection onset
    onset_flags = roi2plot_time <= 0 & ...
        [roi2plot_time(2:end),nan] > 0;
    plot(sps(pc),roi2plot_time(onset_flags),...
        s1_s1_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',s1_clr);
    
    % iterate through stimuli
    for tt = 1 : n_t
        t1_flags = t1 == t_set(tt);
        trial_flags = ...
            valid_flags & ...
            t1_flags;
        if sum(trial_flags) < 1
            continue;
        end
        
        % plot projection offset
        offset_flags = roi2plot_time < t_set(tt) & ...
            [roi2plot_time(2:end),nan] >= t_set(tt);
        scatter(sps(pc),roi2plot_time(offset_flags),...
            s1_s1_score(offset_flags,pc),36,...
            'linewidth',1.5,...
            'marker','o',...
            'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
            'markerfacecolor',s1_clr,...
            'markeredgecolor','none');
    end
    
    % annotate explained variance
    text(sps(pc),...
        .05,1.1,sprintf('%.1f ± %.1f%% var. exp.',...
        s1_s1_exp_avg(pc),...
        s1_s1_exp_err(pc)),...
        'color',s1_clr,...
        'units','normalized');
    
    % ui stacking
    uistack(p,'bottom');
    
    % plot projection
    p = plot(sps(pc),isi_time + t_set(end),...
        s1_isi_score(:,pc),...
        'color',isi_clr,...
        'linestyle','-',...
        'linewidth',1.5);
    
    % plot projection onset
    onset_flags = isi_time <= 0 & ...
        [isi_time(2:end),nan] > 0;
    plot(sps(pc),isi_time(onset_flags) + t_set(end),...
        s1_isi_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',isi_clr);
    
    % plot projection offset
    offset_flags = isi_time < isi & ...
        [isi_time(2:end),nan] >= isi;
    scatter(sps(pc),isi_time(offset_flags) + t_set(end),...
        s1_isi_score(offset_flags,pc),36,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacecolor',isi_clr,...
        'markeredgecolor','none');
    
    % annotate explained variance
    text(sps(pc),...
        .05,1,sprintf('%.1f ± %.1f%% var. exp.',...
        s1_isi_exp_avg(pc),...
        s1_isi_exp_err(pc)),...
        'color',isi_clr,...
        'units','normalized');
    
    % ui stacking
    uistack(p,'bottom');
    
    % compute surviving trial counts (through time)
    time_mat = repmat(...
        roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
    surviving_trial_counts = sum(time_mat(valid_flags,:) <= t2(valid_flags));
    
    % patch projection
    mu_xpatch = roi2plot_time + isi + t_set(end);
    mu_ypatch = s1_s2_score(:,pc)';
    mu_ypatch(end) = nan;
    mu_apatch = surviving_trial_counts;
    mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
        range(alphabounds_mu) + alphabounds_mu(1);
    if fadeifnoisy
        alpha_levels = unique(mu_apatch,'stable');
        n_alpha_levels = numel(alpha_levels);
        for aa = 1 : n_alpha_levels
            alpha_flags = mu_apatch == alpha_levels(aa);
            p = patch(sps(pc),...
                [mu_xpatch(alpha_flags),nan],...
                [mu_ypatch(alpha_flags),nan],0,...
                'edgealpha',alpha_levels(aa),...
                'edgecolor',s2_clr,...
                'facecolor','none',...
                'linewidth',1.5);
        end
    else
        p = plot(sps(pc),roi2plot_time + isi + t_set(end),...
            s1_s2_score(:,pc),...
            'color',s2_clr,...
            'linestyle','-',...
            'linewidth',1.5);
    end
    
    % plot projection onset
    onset_flags = roi2plot_time <= 0 & ...
        [roi2plot_time(2:end),nan] > 0;
    plot(sps(pc),roi2plot_time(onset_flags) + isi + t_set(end),...
        s1_s2_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',s2_clr);
    
    % iterate through stimuli
    for tt = 1 : n_t
        t2_flags = t2 == t_set(tt);
        trial_flags = ...
            valid_flags & ...
            t2_flags;
        if sum(trial_flags) < 1
            continue;
        end
        
        % plot projection offset
        offset_flags = roi2plot_time < t_set(tt) & ...
            [roi2plot_time(2:end),nan] >= t_set(tt);
        scatter(sps(pc),roi2plot_time(offset_flags) + isi + t_set(end),...
            s1_s2_score(offset_flags,pc),36,...
            'linewidth',1.5,...
            'marker','o',...
            'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
            'markerfacecolor',s2_clr,...
            'markeredgecolor','none');
    end
    
    % update axes
    set(sps(pc),...
        'ytick',unique([0,ylim(sps(pc))]),...
        'yticklabel',{'','0',''},...
        'ylim',ylim(sps(pc))+[-1,1]*.15*range(ylim(sps(pc))));
    
    % annotate explained variance
    text(sps(pc),...
        .05,.9,sprintf('%.1f ± %.1f%% var. exp.',...
        s1_s2_exp_avg(pc),...
        s1_s2_exp_err(pc)),...
        'color',s2_clr,...
        'units','normalized');
    
    % ui stacking
    uistack(p,'bottom');
end

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% ISI-aligned PC projections

% figure initialization
fig = figure(figopt,...
    'position',[600,130,966,860],...
    'name','pc_projections_isi');
sps = gobjects(n_pcs2keep,1);
for pc = 1 : n_pcs2keep
    sps(pc) = subplot(n_pcs2keep,1,pc);
    xlabel(sps(pc),'Time since ISI onset (ms)');
    ylabel(sps(pc),sprintf('ISI-aligned PC %i',pc));
end
xxlim = t_set(end) * [-1,1] + [-1,0] * (isi + pre_padd) + isi;
xxtick = unique([[roi2plot';0;t_set];-isi;[roi2plot';0;t_set]-isi-t_set(end)]+isi);
xxticklabel = num2cell(xxtick);
xxticklabel(~ismember(xxtick,...
    [-isi-t_set(end)-pre_padd,-isi-t_set(end),-isi,-pre_padd,0,t_set(end)]+isi)) = {''};
set(sps,...
    axesopt.default,...
    'plotboxaspectratio',[4,1,1],...
    'ticklength',axesopt.default.ticklength * 1/2,...
    'xlim',xxlim + [-1,1] * .05 * 1/4 * range(xxlim),...
    'xtick',xxtick,...
    'xticklabel',xxticklabel,...
    'ylimspec','tight');

% link axes
linkaxes(sps,'x');

% iterate through pcs
for pc = 1 : n_pcs2keep
    
    % compute surviving trial counts (through time)
    time_mat = repmat(...
        roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
    surviving_trial_counts = sum(time_mat(valid_flags,:) <= t1(valid_flags));
    
    % patch projection
    mu_xpatch = roi2plot_time - t_set(end);
    mu_ypatch = isi_s1_score(:,pc)';
    mu_ypatch(end) = nan;
    mu_apatch = surviving_trial_counts;
    mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
        range(alphabounds_mu) + alphabounds_mu(1);
    if fadeifnoisy
        alpha_levels = unique(mu_apatch,'stable');
        n_alpha_levels = numel(alpha_levels);
        for aa = 1 : n_alpha_levels
            alpha_flags = mu_apatch == alpha_levels(aa);
            p = patch(sps(pc),...
                [mu_xpatch(alpha_flags),nan],...
                [mu_ypatch(alpha_flags),nan],0,...
                'edgealpha',alpha_levels(aa),...
                'edgecolor',s1_clr,...
                'facecolor','none',...
                'linewidth',1.5);
        end
    else
        p = plot(sps(pc),roi2plot_time - t_set(end),...
            isi_s1_score(:,pc),...
            'color',s1_clr,...
            'linestyle','-',...
            'linewidth',1.5);
    end
    
    % plot projection onset
    onset_flags = roi2plot_time <= 0 & ...
        [roi2plot_time(2:end),nan] > 0;
    plot(sps(pc),roi2plot_time(onset_flags) - t_set(end),...
        isi_s1_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',s1_clr);
    
    % iterate through stimuli
    for tt = 1 : n_t
        t1_flags = t1 == t_set(tt);
        trial_flags = ...
            valid_flags & ...
            t1_flags;
        if sum(trial_flags) < 1
            continue;
        end
        
        % plot projection offset
        offset_flags = roi2plot_time < t_set(tt) & ...
            [roi2plot_time(2:end),nan] >= t_set(tt);
        scatter(sps(pc),roi2plot_time(offset_flags) - t_set(end),...
            isi_s1_score(offset_flags,pc),36,...
            'linewidth',1.5,...
            'marker','o',...
            'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
            'markerfacecolor',s1_clr,...
            'markeredgecolor','none');
    end
    
    % annotate explained variance
    text(sps(pc),...
        .05,1.1,sprintf('%.1f ± %.1f%% var. exp.',...
        isi_s1_exp_avg(pc),...
        isi_s1_exp_err(pc)),...
        'color',s1_clr,...
        'units','normalized');
    
    % ui stacking
    uistack(p,'bottom');
    
    % plot projection
    p = plot(sps(pc),isi_time,...
        isi_isi_score(:,pc),...
        'color',isi_clr,...
        'linestyle','-',...
        'linewidth',1.5);
    
    % plot projection onset
    onset_flags = isi_time <= 0 & ...
        [isi_time(2:end),nan] > 0;
    plot(sps(pc),isi_time(onset_flags),...
        isi_isi_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',isi_clr);
    
    % plot projection offset
    offset_flags = isi_time < isi & ...
        [isi_time(2:end),nan] >= isi;
    scatter(sps(pc),isi_time(offset_flags),...
        isi_isi_score(offset_flags,pc),36,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacecolor',isi_clr,...
        'markeredgecolor','none');
    
    % annotate explained variance
    text(sps(pc),...
        .05,1,sprintf('%.1f ± %.1f%% var. exp.',...
        isi_isi_exp_avg(pc),...
        isi_isi_exp_err(pc)),...
        'color',isi_clr,...
        'units','normalized');
    
    % ui stacking
    uistack(p,'bottom');
    
    % compute surviving trial counts (through time)
    time_mat = repmat(...
        roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
    surviving_trial_counts = sum(time_mat(valid_flags,:) <= t2(valid_flags));
    
    % patch projection
    mu_xpatch = roi2plot_time + isi;
    mu_ypatch = isi_s2_score(:,pc)';
    mu_ypatch(end) = nan;
    mu_apatch = surviving_trial_counts;
    mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
        range(alphabounds_mu) + alphabounds_mu(1);
    if fadeifnoisy
        alpha_levels = unique(mu_apatch,'stable');
        n_alpha_levels = numel(alpha_levels);
        for aa = 1 : n_alpha_levels
            alpha_flags = mu_apatch == alpha_levels(aa);
            p = patch(sps(pc),...
                [mu_xpatch(alpha_flags),nan],...
                [mu_ypatch(alpha_flags),nan],0,...
                'edgealpha',alpha_levels(aa),...
                'edgecolor',s2_clr,...
                'facecolor','none',...
                'linewidth',1.5);
        end
    else
        p = plot(sps(pc),roi2plot_time + isi,...
            isi_s2_score(:,pc),...
            'color',s2_clr,...
            'linestyle','-',...
            'linewidth',1.5);
    end
    
    % plot projection onset
    onset_flags = roi2plot_time <= 0 & ...
        [roi2plot_time(2:end),nan] > 0;
    plot(sps(pc),roi2plot_time(onset_flags) + isi,...
        isi_s2_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',s2_clr);
    
    % iterate through stimuli
    for tt = 1 : n_t
        t2_flags = t2 == t_set(tt);
        trial_flags = ...
            valid_flags & ...
            t2_flags;
        if sum(trial_flags) < 1
            continue;
        end
        
        % plot projection offset
        offset_flags = roi2plot_time < t_set(tt) & ...
            [roi2plot_time(2:end),nan] >= t_set(tt);
        scatter(sps(pc),roi2plot_time(offset_flags) + isi,...
            isi_s2_score(offset_flags,pc),36,...
            'linewidth',1.5,...
            'marker','o',...
            'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
            'markerfacecolor',s2_clr,...
            'markeredgecolor','none');
    end
    
    % annotate explained variance
    text(sps(pc),...
        .05,.9,sprintf('%.1f ± %.1f%% var. exp.',...
        isi_s2_exp_avg(pc),...
        isi_s2_exp_err(pc)),...
        'color',s2_clr,...
        'units','normalized');
    
    % update axes
    set(sps(pc),...
        'ytick',unique([0,ylim(sps(pc))]),...
        'yticklabel',{'','0',''},...
        'ylim',ylim(sps(pc))+[-1,1]*.15*range(ylim(sps(pc))));
    
    % ui stacking
    uistack(p,'bottom');
end

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% S2-aligned PC projections

% figure initialization
fig = figure(figopt,...
    'position',[1035,130,966,860],...
    'name','pc_projections_s2');
sps = gobjects(n_pcs2keep,1);
for pc = 1 : n_pcs2keep
    sps(pc) = subplot(n_pcs2keep,1,pc);
    xlabel(sps(pc),'Time since S_2 onset (ms)');
    ylabel(sps(pc),sprintf('S2-aligned PC %i',pc));
end
xxlim = t_set(end) * [-1,1] + [-1,0] * (isi + pre_padd);
xxtick = unique([[roi2plot';0;t_set];-isi;[roi2plot';0;t_set]-isi-t_set(end)]);
xxticklabel = num2cell(xxtick);
xxticklabel(~ismember(xxtick,...
    [-isi-t_set(end)-pre_padd,-isi-t_set(end),-isi,-pre_padd,0,t_set(end)])) = {''};
set(sps,...
    axesopt.default,...
    'plotboxaspectratio',[4,1,1],...
    'ticklength',axesopt.default.ticklength * 1/2,...
    'xlim',xxlim + [-1,1] * .05 * 1/4 * range(xxlim),...
    'xtick',xxtick,...
    'xticklabel',xxticklabel,...
    'ylimspec','tight');

% link axes
linkaxes(sps,'x');

% iterate through pcs
for pc = 1 : n_pcs2keep
    
    % compute surviving trial counts (through time)
    time_mat = repmat(...
        roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
    surviving_trial_counts = sum(time_mat(valid_flags,:) <= t1(valid_flags));
    
    % patch projection
    mu_xpatch = roi2plot_time - isi - t_set(end);
    mu_ypatch = s2_s1_score(:,pc)';
    mu_ypatch(end) = nan;
    mu_apatch = surviving_trial_counts;
    mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
        range(alphabounds_mu) + alphabounds_mu(1);
    if fadeifnoisy
        alpha_levels = unique(mu_apatch,'stable');
        n_alpha_levels = numel(alpha_levels);
        for aa = 1 : n_alpha_levels
            alpha_flags = mu_apatch == alpha_levels(aa);
            p = patch(sps(pc),...
                [mu_xpatch(alpha_flags),nan],...
                [mu_ypatch(alpha_flags),nan],0,...
                'edgealpha',alpha_levels(aa),...
                'edgecolor',s1_clr,...
                'facecolor','none',...
                'linewidth',1.5);
        end
    else
        p = plot(sps(pc),roi2plot_time - isi - t_set(end),...
            s2_s1_score(:,pc),...
            'color',s1_clr,...
            'linestyle','-',...
            'linewidth',1.5);
    end
    
    % plot projection onset
    onset_flags = roi2plot_time <= 0 & ...
        [roi2plot_time(2:end),nan] > 0;
    plot(sps(pc),roi2plot_time(onset_flags) - isi - t_set(end),...
        s2_s1_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',s1_clr);
    
    % iterate through stimuli
    for tt = 1 : n_t
        t1_flags = t1 == t_set(tt);
        trial_flags = ...
            valid_flags & ...
            t1_flags;
        if sum(trial_flags) < 1
            continue;
        end
        
        % plot projection offset
        offset_flags = roi2plot_time < t_set(tt) & ...
            [roi2plot_time(2:end),nan] >= t_set(tt);
        scatter(sps(pc),roi2plot_time(offset_flags) - isi - t_set(end),...
            s2_s1_score(offset_flags,pc),36,...
            'linewidth',1.5,...
            'marker','o',...
            'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
            'markerfacecolor',s1_clr,...
            'markeredgecolor','none');
    end
    
    % annotate explained variance
    text(sps(pc),...
        .05,1.1,sprintf('%.1f ± %.1f%% var. exp.',...
        s2_s1_exp_avg(pc),...
        s2_s1_exp_err(pc)),...
        'color',s1_clr,...
        'units','normalized');
    
    % ui stacking
    uistack(p,'bottom');
    
    % plot projection
    p = plot(sps(pc),isi_time - isi,...
        s2_isi_score(:,pc),...
        'color',isi_clr,...
        'linestyle','-',...
        'linewidth',1.5);
    
    % plot projection onset
    onset_flags = isi_time <= 0 & ...
        [isi_time(2:end),nan] > 0;
    plot(sps(pc),isi_time(onset_flags) - isi,...
        s2_isi_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',isi_clr);
    
    % plot projection offset
    offset_flags = isi_time < isi & ...
        [isi_time(2:end),nan] >= isi;
    scatter(sps(pc),isi_time(offset_flags) - isi,...
        s2_isi_score(offset_flags,pc),36,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacecolor',isi_clr,...
        'markeredgecolor','none');
    
    % annotate explained variance
    text(sps(pc),...
        .05,1,sprintf('%.1f ± %.1f%% var. exp.',...
        s2_isi_exp_avg(pc),...
        s2_isi_exp_err(pc)),...
        'color',isi_clr,...
        'units','normalized');
    
    % ui stacking
    uistack(p,'bottom');
    
    % compute surviving trial counts (through time)
    time_mat = repmat(...
        roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
    surviving_trial_counts = sum(time_mat(valid_flags,:) <= t2(valid_flags));
    
    % patch projection
    mu_xpatch = roi2plot_time;
    mu_ypatch = s2_s2_score(:,pc)';
    mu_ypatch(end) = nan;
    mu_apatch = surviving_trial_counts;
    mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
        range(alphabounds_mu) + alphabounds_mu(1);
    if fadeifnoisy
        alpha_levels = unique(mu_apatch,'stable');
        n_alpha_levels = numel(alpha_levels);
        for aa = 1 : n_alpha_levels
            alpha_flags = mu_apatch == alpha_levels(aa);
            p = patch(sps(pc),...
                [mu_xpatch(alpha_flags),nan],...
                [mu_ypatch(alpha_flags),nan],0,...
                'edgealpha',alpha_levels(aa),...
                'edgecolor',s2_clr,...
                'facecolor','none',...
                'linewidth',1.5);
        end
    else
        p = plot(sps(pc),roi2plot_time,...
            s2_s2_score(:,pc),...
            'color',s2_clr,...
            'linestyle','-',...
            'linewidth',1.5);
    end
    
    % plot projection onset
    onset_flags = roi2plot_time <= 0 & ...
        [roi2plot_time(2:end),nan] > 0;
    plot(sps(pc),roi2plot_time(onset_flags),...
        s2_s2_score(onset_flags,pc),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',6,...
        'markerfacecolor','w',...
        'markeredgecolor',s2_clr);
    
    % iterate through stimuli
    for tt = 1 : n_t
        t2_flags = t2 == t_set(tt);
        trial_flags = ...
            valid_flags & ...
            t2_flags;
        if sum(trial_flags) < 1
            continue;
        end
        
        % plot projection offset
        offset_flags = roi2plot_time < t_set(tt) & ...
            [roi2plot_time(2:end),nan] >= t_set(tt);
        scatter(sps(pc),roi2plot_time(offset_flags),...
            s2_s2_score(offset_flags,pc),36,...
            'linewidth',1.5,...
            'marker','o',...
            'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
            'markerfacecolor',s2_clr,...
            'markeredgecolor','none');
    end
    
    % annotate explained variance
    text(sps(pc),...
        .05,.9,sprintf('%.1f ± %.1f%% var. exp.',...
        s2_s2_exp_avg(pc),...
        s2_s2_exp_err(pc)),...
        'color',s2_clr,...
        'units','normalized');
    
    % update axes
    set(sps(pc),...
        'ytick',unique([0,ylim(sps(pc))]),...
        'yticklabel',{'','0',''},...
        'ylim',ylim(sps(pc))+[-1,1]*.15*range(ylim(sps(pc))));
    
    % ui stacking
    uistack(p,'bottom');
end

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% 2D trajectories in curated S1-aligned PC space
fig = figure(figopt,...
    'name','pc_trajectories2D_s1');
axes(...
    axesopt.default,...
    'clipping','off');
title('S1-aligned PC subspace');
xlabel('S1-aligned neural dimension 1_{1}');
ylabel('S1-aligned neural dimension 2_{2}');
xlabel('S_{1}-aligned PC 1 score_{1}');
ylabel('S_{1}-aligned PC 2 score_{2}');

% nested PCA approach
R = pca(s1_s1_score(:,1:3),...
    'weights',s1_weights.^1);
R = R .* [1,1,1]';

% basis vectors
B = cat(3,...
    padarray([-1,0,1],2,0,'post'),...
    padarray([-1,0,1],1,0,'both'),...
    padarray([-1,0,1],2,0,'pre')) * 3;

% iterate through bases
for ii = 1 : 3
    
    % apply rotations
    B(:,:,ii) = R * B(:,:,ii);
end

% apply rotations
s1_S = R * s1_s1_score(:,1:3)';
isi_S = R * s1_isi_score(:,1:3)';
s2_S = R * s1_s2_score(:,1:3)';

% compute surviving trial counts (through time)
time_mat = repmat(...
    roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
surviving_trial_counts = sum(time_mat(valid_flags,:) <= t1(valid_flags));

% patch trajectory
mu_xpatch = s1_S(1,:);
mu_ypatch = s1_S(2,:);
mu_ypatch(end) = nan;
mu_apatch = surviving_trial_counts;
mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
    range(alphabounds_mu) + alphabounds_mu(1);
if fadeifnoisy
    alpha_levels = unique(mu_apatch,'stable');
    n_alpha_levels = numel(alpha_levels);
    for aa = 1 : n_alpha_levels
        alpha_flags = mu_apatch == alpha_levels(aa);
        patch(...
            [mu_xpatch(alpha_flags),nan],...
            [mu_ypatch(alpha_flags),nan],0,...
            'edgealpha',alpha_levels(aa),...
            'edgecolor',s1_clr,...
            'facecolor','none',...
            'linewidth',1.5);
    end
else
    plot(s1_S(1,:),...
        s1_S(2,:),...
        'color',s1_clr,...
        'linestyle','-',...
        'linewidth',1.5);
end

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
p = plot(s1_S(1,onset_flags),...
    s1_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s1_clr);

% iterate through stimuli
for tt = 1 : n_t
    t1_flags = t1 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t1_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    scatter(s1_S(1,offset_flags),s1_S(2,offset_flags),7.5^2,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
        'markerfacecolor',s1_clr,...
        'markeredgecolor','none');
end

% ui restacking
uistack(p,'top');

% plot trajectory
plot(isi_S(1,:),...
    isi_S(2,:),...
    'color',isi_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot ISI onset
onset_flags = isi_time <= 0 & ...
    [isi_time(2:end),nan] > 0;
plot(isi_S(1,onset_flags),...
    isi_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',isi_clr);

% plot ISI offset
offset_flags = isi_time < isi & ...
    [isi_time(2:end),nan] >= isi;
scatter(isi_S(1,offset_flags),isi_S(2,offset_flags),7.5^2,...
    'linewidth',1.5,...
    'marker','o',...
    'markerfacealpha',1,...
    'markerfacecolor',isi_clr,...
    'markeredgecolor','none');

% compute surviving trial counts (through time)
time_mat = repmat(...
    roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
surviving_trial_counts = sum(time_mat(valid_flags,:) <= t2(valid_flags));

% patch trajectory
mu_xpatch = s2_S(1,:);
mu_ypatch = s2_S(2,:);
mu_ypatch(end) = nan;
mu_apatch = surviving_trial_counts;
mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
    range(alphabounds_mu) + alphabounds_mu(1);
if fadeifnoisy
    alpha_levels = unique(mu_apatch,'stable');
    n_alpha_levels = numel(alpha_levels);
    for aa = 1 : n_alpha_levels
        alpha_flags = mu_apatch == alpha_levels(aa);
        patch(...
            [mu_xpatch(alpha_flags),nan],...
            [mu_ypatch(alpha_flags),nan],0,...
            'edgealpha',alpha_levels(aa),...
            'edgecolor',s2_clr,...
            'facecolor','none',...
            'linewidth',1.5);
    end
else
    plot(s2_S(1,:),...
        s2_S(2,:),...
        'color',s2_clr,...
        'linestyle','-',...
        'linewidth',1.5);
end

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
p = plot(s2_S(1,onset_flags),...
    s2_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s2_clr);

% iterate through stimuli
for tt = 1 : n_t
    t2_flags = t2 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t2_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    scatter(s2_S(1,offset_flags),s2_S(2,offset_flags),7.5^2,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
        'markerfacecolor',s2_clr,...
        'markeredgecolor','none');
end

% ui restacking
uistack(p,'top');

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k');

% iterate through dimensions
B_clrs = [1,0,0; 0,1,0; 0,0,1];
for ii = 1 : size(B,1)
    
    % plot basis
    plot(B(1,:,ii)+mean(xlim),...
        B(2,:,ii)+mean(ylim),...
        'color',B_clrs(ii,:),...
        'linewidth',1.5,...
        'linestyle','-');
end

% annotate variance explained
text(1,1,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(s1_s1_exp_avg(1:2)),...
    sqrt(sum(s1_s1_exp_err(1:2).^2))),...
    'color',s1_clr,...
    'horizontalalignment','center',...
    'units','normalized');
text(1,.95,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(s1_isi_exp_avg(1:2)),...
    sqrt(sum(s1_isi_exp_err(1:2).^2))),...
    'color',isi_clr,...
    'horizontalalignment','center',...
    'units','normalized');
text(1,.9,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(s1_s2_exp_avg(1:2)),...
    sqrt(sum(s1_s2_exp_err(1:2).^2))),...
    'color',s2_clr,...
    'horizontalalignment','center',...
    'units','normalized');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% 2D trajectories in curated ISI-aligned PC space
fig = figure(figopt,...
    'name','pc_trajectories2D_isi');
axes(...
    axesopt.default,...
    'clipping','off');
title('ISI-aligned PC subspace');
xlabel('ISI-aligned neural dimension 1_{1}');
ylabel('ISI-aligned neural dimension 2_{2}');
xlabel('ISI-aligned PC 1 score_{1}');
ylabel('ISI-aligned PC 2 score_{2}');

% nested PCA approach
R = pca(isi_isi_score(:,1:3),...
    'weights',isi_weights.^1);
R = R .* [1,1,1]';

% basis vectors
B = cat(3,...
    padarray([-1,0,1],2,0,'post'),...
    padarray([-1,0,1],1,0,'both'),...
    padarray([-1,0,1],2,0,'pre')) * 3;

% iterate through bases
for ii = 1 : 3
    
    % apply rotations
    B(:,:,ii) = R * B(:,:,ii);
end

% apply rotations
s1_S = R * isi_s1_score(:,1:3)';
isi_S = R * isi_isi_score(:,1:3)';
s2_S = R * isi_s2_score(:,1:3)';

% compute surviving trial counts (through time)
time_mat = repmat(...
    roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
surviving_trial_counts = sum(time_mat(valid_flags,:) <= t1(valid_flags));

% patch trajectory
mu_xpatch = s1_S(1,:);
mu_ypatch = s1_S(2,:);
mu_ypatch(end) = nan;
mu_apatch = surviving_trial_counts;
mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
    range(alphabounds_mu) + alphabounds_mu(1);
if fadeifnoisy
    alpha_levels = unique(mu_apatch,'stable');
    n_alpha_levels = numel(alpha_levels);
    for aa = 1 : n_alpha_levels
        alpha_flags = mu_apatch == alpha_levels(aa);
        patch(...
            [mu_xpatch(alpha_flags),nan],...
            [mu_ypatch(alpha_flags),nan],0,...
            'edgealpha',alpha_levels(aa),...
            'edgecolor',s1_clr,...
            'facecolor','none',...
            'linewidth',1.5);
    end
else
    plot(s1_S(1,:),...
        s1_S(2,:),...
        'color',s1_clr,...
        'linestyle','-',...
        'linewidth',1.5);
end

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
p = plot(s1_S(1,onset_flags),...
    s1_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s1_clr);

% iterate through stimuli
for tt = 1 : n_t
    t1_flags = t1 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t1_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    scatter(s1_S(1,offset_flags),s1_S(2,offset_flags),7.5^2,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
        'markerfacecolor',s1_clr,...
        'markeredgecolor','none');
end

% ui restacking
uistack(p,'top');

% plot trajectory
plot(isi_S(1,:),...
    isi_S(2,:),...
    'color',isi_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot ISI onset
onset_flags = isi_time <= 0 & ...
    [isi_time(2:end),nan] > 0;
plot(isi_S(1,onset_flags),...
    isi_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',isi_clr);

% plot ISI offset
offset_flags = isi_time < isi & ...
    [isi_time(2:end),nan] >= isi;
scatter(isi_S(1,offset_flags),isi_S(2,offset_flags),7.5^2,...
    'linewidth',1.5,...
    'marker','o',...
    'markerfacealpha',1,...
    'markerfacecolor',isi_clr,...
    'markeredgecolor','none');

% compute surviving trial counts (through time)
time_mat = repmat(...
    roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
surviving_trial_counts = sum(time_mat(valid_flags,:) <= t2(valid_flags));

% patch trajectory
mu_xpatch = s2_S(1,:);
mu_ypatch = s2_S(2,:);
mu_ypatch(end) = nan;
mu_apatch = surviving_trial_counts;
mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
    range(alphabounds_mu) + alphabounds_mu(1);
if fadeifnoisy
    alpha_levels = unique(mu_apatch,'stable');
    n_alpha_levels = numel(alpha_levels);
    for aa = 1 : n_alpha_levels
        alpha_flags = mu_apatch == alpha_levels(aa);
        patch(...
            [mu_xpatch(alpha_flags),nan],...
            [mu_ypatch(alpha_flags),nan],0,...
            'edgealpha',alpha_levels(aa),...
            'edgecolor',s2_clr,...
            'facecolor','none',...
            'linewidth',1.5);
    end
else
    plot(s2_S(1,:),...
        s2_S(2,:),...
        'color',s2_clr,...
        'linestyle','-',...
        'linewidth',1.5);
end

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
p = plot(s2_S(1,onset_flags),...
    s2_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s2_clr);

% iterate through stimuli
for tt = 1 : n_t
    t2_flags = t2 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t2_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    scatter(s2_S(1,offset_flags),s2_S(2,offset_flags),7.5^2,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
        'markerfacecolor',s2_clr,...
        'markeredgecolor','none');
end

% ui restacking
uistack(p,'top');

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k');

% iterate through dimensions
B_clrs = [1,0,0; 0,1,0; 0,0,1];
for ii = 1 : size(B,1)
    
    % plot basis
    plot(B(1,:,ii)+mean(xlim),...
        B(2,:,ii)+mean(ylim),...
        'color',B_clrs(ii,:),...
        'linewidth',1.5,...
        'linestyle','-');
end

% annotate variance explained
text(1,1,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(isi_s1_exp_avg(1:2)),...
    sqrt(sum(isi_s1_exp_err(1:2).^2))),...
    'color',s1_clr,...
    'horizontalalignment','center',...
    'units','normalized');
text(1,.95,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(isi_isi_exp_avg(1:2)),...
    sqrt(sum(isi_isi_exp_err(1:2).^2))),...
    'color',isi_clr,...
    'horizontalalignment','center',...
    'units','normalized');
text(1,.9,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(isi_s2_exp_avg(1:2)),...
    sqrt(sum(isi_s2_exp_err(1:2).^2))),...
    'color',s2_clr,...
    'horizontalalignment','center',...
    'units','normalized');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% 2D trajectories in curated S2-aligned PC space
fig = figure(figopt,...
    'name','pc_trajectories2D_s2');
axes(...
    axesopt.default,...
    'clipping','off');
title('S2-aligned PC subspace');
xlabel('S_{2}-aligned neural dimension 1_{1}');
ylabel('S_{2}-aligned neural dimension 2_{2}');
xlabel('S_{2}-aligned PC 1 score_{1}');
ylabel('S_{2}-aligned PC 2 score_{2}');

% nested PCA approach
R = pca(s2_s2_score(:,1:3),...
    'weights',s2_weights.^1);
R = R .* [1,1,1]';

% basis vectors
B = cat(3,...
    padarray([-1,0,1],2,0,'post'),...
    padarray([-1,0,1],1,0,'both'),...
    padarray([-1,0,1],2,0,'pre')) * 3;

% iterate through bases
for ii = 1 : 3
    
    % apply rotations
    B(:,:,ii) = R * B(:,:,ii);
end

% apply rotations
s1_S = R * s2_s1_score(:,1:3)';
isi_S = R * s2_isi_score(:,1:3)';
s2_S = R * s2_s2_score(:,1:3)';

% compute surviving trial counts (through time)
time_mat = repmat(...
    roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
surviving_trial_counts = sum(time_mat(valid_flags,:) <= t1(valid_flags));

% patch trajectory
mu_xpatch = s1_S(1,:);
mu_ypatch = s1_S(2,:);
mu_ypatch(end) = nan;
mu_apatch = surviving_trial_counts;
mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
    range(alphabounds_mu) + alphabounds_mu(1);
if fadeifnoisy
    alpha_levels = unique(mu_apatch,'stable');
    n_alpha_levels = numel(alpha_levels);
    for aa = 1 : n_alpha_levels
        alpha_flags = mu_apatch == alpha_levels(aa);
        patch(...
            [mu_xpatch(alpha_flags),nan],...
            [mu_ypatch(alpha_flags),nan],0,...
            'edgealpha',alpha_levels(aa),...
            'edgecolor',s1_clr,...
            'facecolor','none',...
            'linewidth',1.5);
    end
else
    plot(s1_S(1,:),...
        s1_S(2,:),...
        'color',s1_clr,...
        'linestyle','-',...
        'linewidth',1.5);
end

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
p = plot(s1_S(1,onset_flags),...
    s1_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s1_clr);

% iterate through stimuli
for tt = 1 : n_t
    t1_flags = t1 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t1_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    scatter(s1_S(1,offset_flags),s1_S(2,offset_flags),7.5^2,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
        'markerfacecolor',s1_clr,...
        'markeredgecolor','none');
end

% ui restacking
uistack(p,'top');

% plot trajectory
plot(isi_S(1,:),...
    isi_S(2,:),...
    'color',isi_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot ISI onset
onset_flags = isi_time <= 0 & ...
    [isi_time(2:end),nan] > 0;
plot(isi_S(1,onset_flags),...
    isi_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',isi_clr);

% plot ISI offset
offset_flags = isi_time < isi & ...
    [isi_time(2:end),nan] >= isi;
scatter(isi_S(1,offset_flags),isi_S(2,offset_flags),7.5^2,...
    'linewidth',1.5,...
    'marker','o',...
    'markerfacealpha',1,...
    'markerfacecolor',isi_clr,...
    'markeredgecolor','none');

% compute surviving trial counts (through time)
time_mat = repmat(...
    roi2plot_padded(1) + psthbin : psthbin : roi2plot_padded(2),n_total_trials,1);
surviving_trial_counts = sum(time_mat(valid_flags,:) <= t2(valid_flags));

% patch trajectory
mu_xpatch = s2_S(1,:);
mu_ypatch = s2_S(2,:);
mu_ypatch(end) = nan;
mu_apatch = surviving_trial_counts;
mu_apatch = mu_apatch ./ max(mu_apatch) .* ...
    range(alphabounds_mu) + alphabounds_mu(1);
if fadeifnoisy
    alpha_levels = unique(mu_apatch,'stable');
    n_alpha_levels = numel(alpha_levels);
    for aa = 1 : n_alpha_levels
        alpha_flags = mu_apatch == alpha_levels(aa);
        patch(...
            [mu_xpatch(alpha_flags),nan],...
            [mu_ypatch(alpha_flags),nan],0,...
            'edgealpha',alpha_levels(aa),...
            'edgecolor',s2_clr,...
            'facecolor','none',...
            'linewidth',1.5);
    end
else
    plot(s2_S(1,:),...
        s2_S(2,:),...
        'color',s2_clr,...
        'linestyle','-',...
        'linewidth',1.5);
end

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
p = plot(s2_S(1,onset_flags),...
    s2_S(2,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s2_clr);

% iterate through stimuli
for tt = 1 : n_t
    t2_flags = t2 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t2_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    scatter(s2_S(1,offset_flags),s2_S(2,offset_flags),7.5^2,...
        'linewidth',1.5,...
        'marker','o',...
        'markerfacealpha',alpha_levels(tt).^fadeifnoisy,...
        'markerfacecolor',s2_clr,...
        'markeredgecolor','none');
end

% ui restacking
uistack(p,'top');

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k');

% iterate through dimensions
B_clrs = [1,0,0; 0,1,0; 0,0,1];
for ii = 1 : size(B,1)
    
    % plot basis
    plot(B(1,:,ii)+mean(xlim),...
        B(2,:,ii)+mean(ylim),...
        'color',B_clrs(ii,:),...
        'linewidth',1.5,...
        'linestyle','-');
end

% annotate variance explained
text(1,1,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(s2_s1_exp_avg(1:2)),...
    sqrt(sum(s2_s1_exp_err(1:2).^2))),...
    'color',s1_clr,...
    'horizontalalignment','center',...
    'units','normalized');
text(1,.95,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(s2_isi_exp_avg(1:2)),...
    sqrt(sum(s2_isi_exp_err(1:2).^2))),...
    'color',isi_clr,...
    'horizontalalignment','center',...
    'units','normalized');
text(1,.9,sprintf('%.1f ± %.1f%% var. exp.',...
    sum(s2_s2_exp_avg(1:2)),...
    sqrt(sum(s2_s2_exp_err(1:2).^2))),...
    'color',s2_clr,...
    'horizontalalignment','center',...
    'units','normalized');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% S1-aligned PC coefficient scatter
fig = figure(figopt,...
    'name','pc_coefficients2D_s1');
axes(...
    axesopt.default,...
    'clipping','off');
xlabel('S_{1}-aligned PC 1 coefficient_{1}');
ylabel('S_{1}-aligned PC 2 coefficient_{2}');

% coefficient scatter
grapeplot(s1_coeff(:,1),s1_coeff(:,2),...
    'markerfacecolor',s1_clr);

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% ISI-aligned PC coefficient scatter
fig = figure(figopt,...
    'name','pc_coefficients2D_isi');
axes(...
    axesopt.default,...
    'clipping','off');
xlabel('ISI-aligned PC 1 coefficient_{1}');
ylabel('ISI-aligned PC 2 coefficient_{2}');

% coefficient scatter
grapeplot(isi_coeff(:,1),isi_coeff(:,2),...
    'markerfacecolor',isi_clr);

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% S2-aligned PC coefficient scatter
fig = figure(figopt,...
    'name','pc_coefficients2D_s2');
axes(...
    axesopt.default,...
    'clipping','off');
xlabel('S_{2}-aligned PC 1 coefficient_{1}');
ylabel('S_{2}-aligned PC 2 coefficient_{2}');

% coefficient scatter
grapeplot(s2_coeff(:,1),s2_coeff(:,2),...
    'markerfacecolor',s2_clr);

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%%
coeff_prefix = 's2';
maxK = 6;
maxPCs = 10;
figure;
hold on;
set(gca,...
    'plotboxaspectratio',[1,1,1],...
    'xlim',[0,maxK+1],...
    'xtick',1:maxK);
xlabel('Number of clusters');
ylabel('Gap value');
k_clrs = cool(maxPCs-1);
for kk = 2 : maxPCs
    progressreport(kk-1,maxPCs-1,'');
    evaluation = evalclusters(...
        eval([coeff_prefix,'_coeff(:,1:kk)']),'kmeans','gap',...
        'klist',1:maxK);
    errorbar(evaluation.InspectedK,evaluation.CriterionValues,evaluation.SE,...
        'color',k_clrs(kk-1,:));
end
leg_str = arrayfun(@(x)sprintf('first %i PCs_{%s}',x,coeff_prefix),2:maxPCs,...
    'uniformoutput',false);
legend(leg_str);

%% 3D trajectories in curated S1-aligned PC space
fig = figure(figopt,...
    'name','pc_trajectories3D_s1');
axes(...
    axesopt.default,...
    'clipping','off');
title('S1-aligned PC subspace');
xlabel('PC 1');
ylabel('PC 2');
zlabel('PC 3');
view(45,30);

% fetch PC projections
s1_S = s1_s1_score(:,1:3)';
isi_S = s1_isi_score(:,1:3)';
s2_S = s1_s2_score(:,1:3)';

% plot trajectory
plot3(s1_S(1,:),...
    s1_S(2,:),...
    s1_S(3,:),...
    'color',s1_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
plot3(s1_S(1,onset_flags),...
    s1_S(2,onset_flags),...
    s1_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s1_clr);

% iterate through stimuli
for tt = 1 : n_t
    t1_flags = t1 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t1_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    plot3(s1_S(1,offset_flags),...
        s1_S(2,offset_flags),...
        s1_S(3,offset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',7.5,...
        'markerfacecolor',s1_clr,...
        'markeredgecolor','none');
end

% plot trajectory
plot3(isi_S(1,:),...
    isi_S(2,:),...
    isi_S(3,:),...
    'color',isi_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot ISI onset
onset_flags = isi_time <= 0 & ...
    [isi_time(2:end),nan] > 0;
plot3(isi_S(1,onset_flags),...
    isi_S(2,onset_flags),...
    isi_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',isi_clr);

% plot ISI offset
offset_flags = isi_time < isi & ...
    [isi_time(2:end),nan] >= isi;
plot3(isi_S(1,offset_flags),...
    isi_S(2,offset_flags),...
    isi_S(3,offset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor',isi_clr,...
    'markeredgecolor','none');

% plot trajectory
plot3(s2_S(1,:),...
    s2_S(2,:),...
    s2_S(3,:),...
    'color',s2_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
plot3(s2_S(1,onset_flags),...
    s2_S(2,onset_flags),...
    s2_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s2_clr);

% iterate through stimuli
for tt = 1 : n_t
    t2_flags = t2 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t2_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    plot3(s2_S(1,offset_flags),...
        s2_S(2,offset_flags),...
        s2_S(3,offset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',7.5,...
        'markerfacecolor',s2_clr,...
        'markeredgecolor','none');
end

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
zzlim = zlim + [-1,1] * .05 * range(zlim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
zlim(zzlim + [-1,1] * spacer * range(zzlim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'ztick',unique([zzlim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'zticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k',...
    'zcolor','k');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% 3D trajectories in curated ISI-aligned PC space
fig = figure(figopt,...
    'name','pc_trajectories3D_isi');
axes(...
    axesopt.default,...
    'clipping','off');
title('ISI-aligned PC subspace');
xlabel('PC 1');
ylabel('PC 2');
zlabel('PC 3');
view(45,30);

% fetch PC projections
s1_S = isi_s1_score(:,1:3)';
isi_S = isi_isi_score(:,1:3)';
s2_S = isi_s2_score(:,1:3)';

% plot trajectory
plot3(s1_S(1,:),...
    s1_S(2,:),...
    s1_S(3,:),...
    'color',s1_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
plot3(s1_S(1,onset_flags),...
    s1_S(2,onset_flags),...
    s1_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s1_clr);

% iterate through stimuli
for tt = 1 : n_t
    t1_flags = t1 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t1_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    plot3(s1_S(1,offset_flags),...
        s1_S(2,offset_flags),...
        s1_S(3,offset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',7.5,...
        'markerfacecolor',s1_clr,...
        'markeredgecolor','none');
end

% plot trajectory
plot3(isi_S(1,:),...
    isi_S(2,:),...
    isi_S(3,:),...
    'color',isi_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot ISI onset
onset_flags = isi_time <= 0 & ...
    [isi_time(2:end),nan] > 0;
plot3(isi_S(1,onset_flags),...
    isi_S(2,onset_flags),...
    isi_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',isi_clr);

% plot ISI offset
offset_flags = isi_time < isi & ...
    [isi_time(2:end),nan] >= isi;
plot3(isi_S(1,offset_flags),...
    isi_S(2,offset_flags),...
    isi_S(3,offset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor',isi_clr,...
    'markeredgecolor','none');

% plot trajectory
plot3(s2_S(1,:),...
    s2_S(2,:),...
    s2_S(3,:),...
    'color',s2_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
plot3(s2_S(1,onset_flags),...
    s2_S(2,onset_flags),...
    s2_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s2_clr);

% iterate through stimuli
for tt = 1 : n_t
    t2_flags = t2 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t2_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    plot3(s2_S(1,offset_flags),...
        s2_S(2,offset_flags),...
        s2_S(3,offset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',7.5,...
        'markerfacecolor',s2_clr,...
        'markeredgecolor','none');
end

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
zzlim = zlim + [-1,1] * .05 * range(zlim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
zlim(zzlim + [-1,1] * spacer * range(zzlim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'ztick',unique([zzlim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'zticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k',...
    'zcolor','k');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% 3D trajectories in curated S2-aligned PC space
fig = figure(figopt,...
    'name','pc_trajectories3D_s2');
axes(...
    axesopt.default,...
    'clipping','off');
title('S2-aligned PC subspace');
xlabel('PC 1');
ylabel('PC 2');
zlabel('PC 3');
view(45,30);

% fetch PC projections
s1_S = s2_s1_score(:,1:3)';
isi_S = s2_isi_score(:,1:3)';
s2_S = s2_s2_score(:,1:3)';

% plot trajectory
plot3(s1_S(1,:),...
    s1_S(2,:),...
    s1_S(3,:),...
    'color',s1_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
plot3(s1_S(1,onset_flags),...
    s1_S(2,onset_flags),...
    s1_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s1_clr);

% iterate through stimuli
for tt = 1 : n_t
    t1_flags = t1 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t1_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    plot3(s1_S(1,offset_flags),...
        s1_S(2,offset_flags),...
        s1_S(3,offset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',7.5,...
        'markerfacecolor',s1_clr,...
        'markeredgecolor','none');
end

% plot trajectory
plot3(isi_S(1,:),...
    isi_S(2,:),...
    isi_S(3,:),...
    'color',isi_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot ISI onset
onset_flags = isi_time <= 0 & ...
    [isi_time(2:end),nan] > 0;
plot3(isi_S(1,onset_flags),...
    isi_S(2,onset_flags),...
    isi_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',isi_clr);

% plot ISI offset
offset_flags = isi_time < isi & ...
    [isi_time(2:end),nan] >= isi;
plot3(isi_S(1,offset_flags),...
    isi_S(2,offset_flags),...
    isi_S(3,offset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor',isi_clr,...
    'markeredgecolor','none');

% plot trajectory
plot3(s2_S(1,:),...
    s2_S(2,:),...
    s2_S(3,:),...
    'color',s2_clr,...
    'linestyle','-',...
    'linewidth',1.5);

% plot stimulus onset
onset_flags = roi2plot_time <= 0 & ...
    [roi2plot_time(2:end),nan] > 0;
plot3(s2_S(1,onset_flags),...
    s2_S(2,onset_flags),...
    s2_S(3,onset_flags),...
    'linewidth',1.5,...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor',s2_clr);

% iterate through stimuli
for tt = 1 : n_t
    t2_flags = t2 == t_set(tt);
    trial_flags = ...
        valid_flags & ...
        t2_flags;
    if sum(trial_flags) < 1
        continue;
    end
    
    % plot stimulus offset
    offset_flags = roi2plot_time < t_set(tt) & ...
        [roi2plot_time(2:end),nan] >= t_set(tt);
    plot3(s2_S(1,offset_flags),...
        s2_S(2,offset_flags),...
        s2_S(3,offset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',7.5,...
        'markerfacecolor',s2_clr,...
        'markeredgecolor','none');
end

% update axis
axis tight;
xxlim = xlim + [-1,1] * .05 * range(xlim);
yylim = ylim + [-1,1] * .05 * range(ylim);
zzlim = zlim + [-1,1] * .05 * range(zlim);
spacer = .05;
xlim(xxlim + [-1,1] * spacer * range(xxlim));
ylim(yylim + [-1,1] * spacer * range(yylim));
zlim(zzlim + [-1,1] * spacer * range(zzlim));
set(gca,...
    'xtick',unique([xxlim,0]),...
    'ytick',unique([yylim,0]),...
    'ztick',unique([zzlim,0]),...
    'xticklabel',{'','0',''},...
    'yticklabel',{'','0',''},...
    'zticklabel',{'','0',''},...
    'xcolor','k',...
    'ycolor','k',...
    'zcolor','k');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end