%% initialization
if ~exist('data','var')
    toso2021_wrapper;
end

%% compute Si-aligned stereotypy

% preallocation
fr_tuning = struct(...
    's1',nan(n_neurons,1),...
    's2',nan(n_neurons,1));

% time vector
t = linspace(0,t_set(end),n_tbins);

% iterate through neurons
for nn = 1 : n_neurons_total
    progressreport(nn,n_neurons_total,'parsing neural data');
    neuron_flags = data.NeuronNumb == neuron_idcs(nn);
    spike_flags = ...
        valid_flags & ...
        neuron_flags;
    if sum(spike_flags) == 0 || ~ismember(nn,flagged_neurons)
        continue;
    end
    
    % fetch spike counts & compute spike rates
    spike_rates = data.SDF(spike_flags,:);
    n_trials = size(spike_rates,1);
    
    % S1-aligned spike rates
    s1_alignment = ...
        pre_init_padding + ...
        pre_s1_delay(spike_flags);
    s1_alignment_flags = ...
        padded_time >= s1_alignment & ...
        padded_time < s1_alignment + t1(spike_flags);
    s1_chunk_flags = ...
        padded_time >= s1_alignment & ...
        padded_time < s1_alignment + t_set(end);
    s1_spkrates = spike_rates';
    s1_spkrates(~s1_alignment_flags') = nan;
    s1_spkrates = reshape(...
        s1_spkrates(s1_chunk_flags'),[n_tbins,n_trials])';
    
    % S2-aligned spike rates
    s2_alignment = ...
        pre_init_padding + ...
        pre_s1_delay(spike_flags) + ...
        t1(spike_flags) + ...
        isi;
    s2_alignment_flags = ...
        padded_time >= s2_alignment & ...
        padded_time < s2_alignment + t2(spike_flags);
    s2_chunk_flags = ...
        padded_time >= s2_alignment & ...
        padded_time < s2_alignment + t_set(end);
    s2_spkrates = spike_rates';
    s2_spkrates(~s2_alignment_flags') = nan;
    s2_spkrates = reshape(...
        s2_spkrates(s2_chunk_flags'),[n_tbins,n_trials])';
    
    % compute average spike rates across trials
    s1_spkrate = mean(s1_spkrates,'omitnan');
    s2_spkrate = mean(s2_spkrates,'omitnan');
    
    % normalize
%     s1_spkrate = s1_spkrate - min(s1_spkrate);
%     s2_spkrate = s2_spkrate - min(s2_spkrate);
    s1_spkrate = s1_spkrate ./ nansum(s1_spkrate);
    s2_spkrate = s2_spkrate ./ nansum(s2_spkrate);

    % compute stereotypy coefficient
    fr_tuning.s1(nn) = s1_spkrate * t';
    fr_tuning.s2(nn) = s2_spkrate * t';
end

%% plot firing rate of ramping & non-ramping neurons across task epochs

% figure initialization
fig = figure(figopt,...
    'position',[200 200 560 412.5],...
    'name','ramp_fr_tuning');

% epoch settings
epochs = fieldnames(fr_tuning);
n_epochs = numel(epochs);

% axes initialization
xxoffset = .25;
xxoffsets = [-1,1] * xxoffset;
xxtick = unique((1:n_epochs)+[-1;0;1]*xxoffset);
xxticklabel = num2cell(xxtick);
xxticklabel(~ismember(xxtick,1:n_epochs)) = {''};
xxticklabel(ismember(xxtick,1:n_epochs)) = cellfun(@capitalize,epochs,...
    'uniformoutput',false);
axes(axesopt.default,...
    'plotboxaspectratio',[1,2.25,1],...
    'color','none',...
    'xlim',[1,n_epochs]+[-1,1]*xxoffset*3,...
    'xtick',xxtick,...
    'xticklabel',xxticklabel,...
    'ylimspec','tight',...
    'yaxislocation','right',...
    'clipping','off',...
    'layer','bottom');
xlabel('Stimulus period');
ylabel('Stereotypy coefficient',...
    'rotation',-90,...
    'verticalalignment','bottom');

% preallocation
distro = struct();
avg = struct();
err = struct();

% choice of average and error functions
avgfun = @(x) nanmean(x);
errfun = @(x) [1,1] .* nanstd(x) / sqrt(numel(x));
avgfun = @(x) nanmedian(x);
errfun = @(x) quantile(x,[.25,.75]) - nanmedian(x);

% iterate through alignments
for ee = 1 : n_epochs
    epoch = epochs{ee};
    distro.(epoch) = {...
        fr_tuning.(epoch)(ramp_idcs.(epoch));...
        fr_tuning.(epoch)(nonramp_idcs.(epoch))};
    avg.(epoch) = [...
        avgfun(fr_tuning.(epoch)(ramp_idcs.(epoch)));...
        avgfun(fr_tuning.(epoch)(nonramp_idcs.(epoch)))];
    err.(epoch) = [...
        errfun(fr_tuning.(epoch)(ramp_idcs.(epoch)));...
        errfun(fr_tuning.(epoch)(nonramp_idcs.(epoch)))];
end

% table conversions
avg = struct2table(avg,...
    'rownames',{'ramping','non-ramping'});
err = struct2table(err,...
    'rownames',{'ramping','non-ramping'});

% iterate through alignments
for ee = 1 : n_epochs
    epoch = epochs{ee};
    plot(ee+xxoffsets,avg.(epoch),...
        'color','k',...
        'linewidth',1.5,...
        'handlevisibility','off');
    for rr = 1 : 2
        errorbar(ee+xxoffsets(rr),avg.(epoch)(rr),...
            err.(epoch)(rr,1),err.(epoch)(rr,2),...
            'color','k',...
            'marker','o',...
            'markersize',7.5,...
            'markeredgecolor','k',...
            'markerfacecolor',ramp_clrs(rr,:),...
            'linewidth',1.5,...
            'capsize',0);
    end
end

% legend
legend({'ramping','non-ramping'},...
    'autoupdate','off',...
    'box','off',...
    'location','southwest');

% update axes
yylim = [0,t_set(end)];
yytick = unique([yylim,linspace(0,yylim(2),4)]);
yyticklabel = num2cell(yytick);
yyticklabel(~ismember(yytick,[0,1])) = {''};
set(gca,...
    'ylim',yylim + [-1,1] * .05 * range(yylim),...
    'ytick',yytick,...
    'yticklabel',yyticklabel);

% zero line
plot(xlim,[0,0],':k');

% iterate through alignments
for ee = 1 : n_epochs
    epoch = epochs{ee};
    xx = [-1,1] * .5 / 3 + ee;
    yy = [1,1] * max(yylim);
    plot([1,1]*ee,[min(ylim),1],':k',...
        'handlevisibility','off');
    plot(xx,yy,...
        'color','k',...
        'linewidth',1.5,...
        'handlevisibility','off');
    [~,pval] = kstest2(distro.(epoch){1},distro.(epoch){2});
    %     pval = kruskalwallis(vertcat(distro.(epoch){:}),[],'off');
    pval = pval * n_epochs;
    if pval < .01
        test_str = '**';
    elseif pval < .05
        test_str = '*';
    else
        test_str = 'n.s.';
    end
    text(mean(xx),mean(yy)-.025*range(ylim),test_str,...
        'color','k',...
        'fontsize',16,...
        'horizontalalignment','center',...
        'verticalalignment','bottom');
end

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%%
figure;
binedges = linspace(t_set(end)*.1,t_set(end)*.9,40);
% iterate through alignments
for ee = 1 : n_epochs
    subplot(n_epochs,1,ee); hold on;
    epoch = epochs{ee};
    for rr = 1 : 2
        histogram(distro.(epoch){rr},binedges,...
            'facecolor',ramp_clrs(rr,:),...
            'normalization','pdf');
    end
end