%% initialization
if ~exist('data','var')
    toso2021_wrapper;
end

%% neuron selection

% selected for being good examples of i2-modulation
if strcmpi(task_str,'duration')
    neurons2plot = [...
        21,35,38,62,72,100,130,205,206,215,224,...
        234,241,391,393,397,402,406,428,...
        441,459,462,470,473,526,544,566];
    neurons2plot = [...
        215,393,402,462,526];
elseif strcmpi(task_str,'intensity')
    neurons2plot = [...
        19,22,30,61,66,70,100,111,112,115,...
        166,238,243,260,344,408,410];
end
% neurons2plot = flagged_neurons;
n_neurons2plot = numel(neurons2plot);

%% version-dependent spike marker
version = ver('matlab');
if contains(version.Release,'2019')
    spike_marker = '.';
else
    spike_marker = '.';
end

%% construct Si-aligned, Ti- & Ii-split psths
time2plot = psthbin : psthbin : post_s2_delay;
time_flags = time2plot <= post_s2_delay;

% iterate through neurons
for nn = 1 : n_neurons2plot
    progressreport(nn,n_neurons2plot,'parsing neural data');
    neuron_flags = data.NeuronNumb == neurons2plot(nn);
    
    % figure initialization
    fig = figure(figopt,...
        ...'windowstate','maximized',...
        'position',[7.5,100,1525,460],...
        'name',sprintf('neuron_%i_%s',neurons2plot(nn),'post_s2'));
    n_rows = 2;
    n_cols = 5;
    n_sps = (n_rows - 1) * n_cols;
    sps = gobjects(n_sps,1);
    for ii = 1 : n_cols
        sps(ii) = subplot(n_rows,n_cols,ii);
        sps(ii+n_cols) = subplot(n_rows,n_cols,n_cols+ii);
    end
    set(sps,...
        axesopt.default,...
        'xlim',[0,post_s2_delay],...
        'xtick',[0,post_s2_delay],...
        'layer','top',...
        'plotboxaspectratiomode','auto',...
        'ylimspec','tight');
    xlabel(sps(1+n_cols),'Time since T_2 offset (s)');
    xlabel(sps(2+n_cols),'Time since T_2 offset (s)');
    xlabel(sps(3+n_cols),'Time since T_2 offset (s)');
    xlabel(sps(4+n_cols),'Time since T_2 offset (s)');
    xlabel(sps(5+n_cols),'Time since T_2 offset (s)');
    ylabel(sps(1),'Firing rate (Hz)');
    ylabel(sps(2),'Firing rate (Hz)');
    ylabel(sps(3),'Firing rate (Hz)');
    ylabel(sps(4),'Firing rate (Hz)');
    ylabel(sps(5),'Firing rate (Hz)');
    ylabel(sps(1+n_cols),'Trial #');
    ylabel(sps(2+n_cols),'Trial #');
    ylabel(sps(3+n_cols),'Trial #');
    ylabel(sps(4+n_cols),'Trial #');
    ylabel(sps(5+n_cols),'Trial #');
    
    % preallocation
    i1_n_trial_counter = 0;
    t1_n_trial_counter = 0;
    i2_n_trial_counter = 0;
    t2_n_trial_counter = 0;
    choice_n_trial_counter = 0;
    i1_boundaries = nan(n_i,1);
    t1_boundaries = nan(n_t,1);
    i2_boundaries = nan(n_i,1);
    t2_boundaries = nan(n_t,1);
    choice_boundaries = nan(n_choices,1);
    
    % iterate through intensities
    for ii = 1 : n_i
        i1_flags = i1 == i_set(ii);
        i1_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            i1_flags;
        if sum(i1_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        i1_spike_counts = data.FR(i1_spike_flags,:);
        i1_spike_rates = conv2(...
            1,kernel.pdf,i1_spike_counts,'valid')' / psthbin * 1e3;
        i1_n_trials = size(i1_spike_counts,1);
        i1_n_tbins = post_s2_delay * psthbin;
        
        % T1-aligned, T1-split spike rates
        i1_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(i1_spike_flags) + ...
            t1(i1_spike_flags) + ...
            isi + ...
            t2(i1_spike_flags);
        i1_alignment_flags = ...
            valid_time >= i1_alignment_onset & ...
            valid_time < i1_alignment_onset + post_s2_delay;
        i1_chunk_flags = i1_alignment_flags;
        i1_spkrates = i1_spike_rates;
        i1_spkrates(~i1_alignment_flags') = nan;
        i1_spkrates = reshape(...
            i1_spkrates(i1_chunk_flags'),[i1_n_tbins,i1_n_trials])';
        
        % compute mean spike density function
        i1_mu = nanmean(i1_spkrates(:,time_flags),1);
        i1_std = nanstd(i1_spkrates(:,time_flags),0,1);
        i1_trials_throughtime = sum(~isnan(i1_spkrates),1);
        i1_sem = i1_std ./ sqrt(i1_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(i1_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        i1_xpatch = [flagged_time,fliplr(flagged_time)];
        i1_ypatch = [i1_mu(~nan_flags)-i1_sem(~nan_flags),...
            fliplr(i1_mu(~nan_flags)+i1_sem(~nan_flags))];
        patch_alpha = [i1_trials_throughtime(~nan_flags),...
            fliplr(i1_trials_throughtime(~nan_flags))].^0;
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(1),i1_xpatch,i1_ypatch,i1_clrs(ii,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        i1_xpatch = flagged_time(~nan_flags);
        i1_ypatch = i1_mu(~nan_flags);
        i1_ypatch(end) = nan;
        patch_alpha = i1_trials_throughtime(~nan_flags).^0;
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(1),i1_xpatch,i1_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',i1_clrs(ii,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(1),time2plot(onset_flags),i1_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',i1_clrs(ii,:));
        
        % plot T1 raster
        i1_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(i1_spike_flags) + ...
            t1(i1_spike_flags) + ...
            isi + ...
            t2(i1_spike_flags));
        i1_trial_idcs = (1 : i1_n_trials)' + i1_n_trial_counter;
        i1_trial_mat = repmat(i1_trial_idcs,1,n_paddedtimebins);
        i1_spike_trials = i1_trial_mat(i1_spike_counts >= 1);
        i1_spike_times = i1_time_mat(i1_spike_counts >= 1);
        trial_sorter = [t1(i1_spike_flags),prev_choices(i1_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + i1_n_trial_counter;
        i1_sorted_trials = resorted_idcs(i1_spike_trials - i1_n_trial_counter);
        plot(sps(1+n_cols),i1_spike_times,i1_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',2,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = [0,1,1,0] .* range(xlim(sps(1))) * .1/2;
        ypatch = [.5,.5,i1_n_trials+.5,i1_n_trials+.5] + i1_n_trial_counter;
        patch(sps(1+n_cols),xpatch,ypatch,i1_clrs(ii,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        i1_n_trial_counter = i1_n_trial_counter + i1_n_trials;
        i1_boundaries(ii) = i1_n_trials;
    end
    
    % iterate through durations
    for tt = n_t : -1 : 1
        t1_flags = t1 == t_set(tt);
        t1_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            t1_flags;
        if sum(t1_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        t1_spike_counts = data.FR(t1_spike_flags,:);
        t1_spike_rates = conv2(...
            1,kernel.pdf,t1_spike_counts,'valid')' / psthbin * 1e3;
        t1_n_trials = size(t1_spike_counts,1);
        t1_n_tbins = post_s2_delay * psthbin;
        
        % T2-aligned, T1-split spike rates
        t1_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(t1_spike_flags) + ...
            t1(t1_spike_flags) + ...
            isi + ...
            t2(t1_spike_flags);
        t1_alignment_flags = ...
            valid_time >= t1_alignment_onset & ...
            valid_time < t1_alignment_onset + post_s2_delay;
        t1_chunk_flags = t1_alignment_flags;
        t1_spkrates = t1_spike_rates;
        t1_spkrates(~t1_alignment_flags') = nan;
        t1_spkrates = reshape(...
            t1_spkrates(t1_chunk_flags'),[t1_n_tbins,t1_n_trials])';
        
        % compute mean spike density function
        t1_mu = nanmean(t1_spkrates(:,time_flags),1);
        t1_std = nanstd(t1_spkrates(:,time_flags),0,1);
        t1_trials_throughtime = sum(~isnan(t1_spkrates),1);
        t1_sem = t1_std ./ sqrt(t1_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(t1_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        t1_xpatch = [flagged_time,fliplr(flagged_time)];
        t1_ypatch = [t1_mu(~nan_flags)-t1_sem(~nan_flags),...
            fliplr(t1_mu(~nan_flags)+t1_sem(~nan_flags))];
        patch_alpha = [t1_trials_throughtime(~nan_flags),...
            fliplr(t1_trials_throughtime(~nan_flags))].^0;
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(2),t1_xpatch,t1_ypatch,t1_clrs(tt,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        t1_xpatch = flagged_time(~nan_flags);
        t1_ypatch = t1_mu(~nan_flags);
        t1_ypatch(end) = nan;
        patch_alpha = t1_trials_throughtime(~nan_flags).^0;
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(2),t1_xpatch,t1_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',t1_clrs(tt,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(2),time2plot(onset_flags),t1_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',t1_clrs(tt,:));
        
        % plot T1 raster
        t1_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(t1_spike_flags) + ...
            t1(t1_spike_flags) + ...
            isi + ...
            t2(t1_spike_flags));
        t1_trial_idcs = (1 : t1_n_trials)' + t1_n_trial_counter;
        t1_trial_mat = repmat(t1_trial_idcs,1,n_paddedtimebins);
        t1_spike_trials = t1_trial_mat(t1_spike_counts >= 1);
        t1_spike_times = t1_time_mat(t1_spike_counts >= 1);
        trial_sorter = [t1(t1_spike_flags),prev_choices(t1_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + t1_n_trial_counter;
        t1_sorted_trials = resorted_idcs(t1_spike_trials - t1_n_trial_counter);
        plot(sps(2+n_cols),t1_spike_times,t1_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',2,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = [0,1,1,0] .* range(xlim(sps(2))) * .1/2;
        ypatch = [.5,.5,t1_n_trials+.5,t1_n_trials+.5] + t1_n_trial_counter;
        patch(sps(2+n_cols),xpatch,ypatch,t1_clrs(tt,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        t1_n_trial_counter = t1_n_trial_counter + t1_n_trials;
        t1_boundaries(tt) = t1_n_trials;
    end
    
    % iterate through intensities
    for ii = 1 : n_i
        i2_flags = i2 == i_set(ii);
        i2_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            i2_flags;
        if sum(i2_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        i2_spike_counts = data.FR(i2_spike_flags,:);
        i2_spike_rates = conv2(...
            1,kernel.pdf,i2_spike_counts,'valid')' / psthbin * 1e3;
        i2_n_trials = size(i2_spike_counts,1);
        i2_n_tbins = post_s2_delay * psthbin;
        
        % T2-aligned, I2-split spike rates
        i2_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(i2_spike_flags) + ...
            t1(i2_spike_flags) + ...
            isi + ...
            t2(i2_spike_flags);
        i2_alignment_flags = ...
            valid_time >= i2_alignment_onset & ...
            valid_time < i2_alignment_onset + post_s2_delay;
        i2_chunk_flags = i2_alignment_flags;
        i2_spkrates = i2_spike_rates;
        i2_spkrates(~i2_alignment_flags') = nan;
        i2_spkrates = reshape(...
            i2_spkrates(i2_chunk_flags'),[i2_n_tbins,i2_n_trials])';
        
        % compute mean spike density function
        i2_mu = nanmean(i2_spkrates(:,time_flags),1);
        i2_std = nanstd(i2_spkrates(:,time_flags),0,1);
        i2_trials_throughtime = sum(~isnan(i2_spkrates),1);
        i2_sem = i2_std ./ sqrt(i2_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(i2_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        i2_xpatch = [flagged_time,fliplr(flagged_time)];
        i2_ypatch = [i2_mu(~nan_flags)-i2_sem(~nan_flags),...
            fliplr(i2_mu(~nan_flags)+i2_sem(~nan_flags))];
        patch_alpha = [i2_trials_throughtime(~nan_flags),...
            fliplr(i2_trials_throughtime(~nan_flags))].^0;
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(3),i2_xpatch,i2_ypatch,i2_clrs(ii,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        i2_xpatch = flagged_time(~nan_flags);
        i2_ypatch = i2_mu(~nan_flags);
        i2_ypatch(end) = nan;
        patch_alpha = i2_trials_throughtime(~nan_flags).^0;
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(3),i2_xpatch,i2_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',i2_clrs(ii,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(3),time2plot(onset_flags),i2_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',i2_clrs(ii,:));
        
        % plot I2 raster
        i2_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(i2_spike_flags) + ...
            t1(i2_spike_flags) + ...
            isi + ...
            t2(i2_spike_flags));
        i2_trial_idcs = (1 : i2_n_trials)' + i2_n_trial_counter;
        i2_trial_mat = repmat(i2_trial_idcs,1,n_paddedtimebins);
        i2_spike_trials = i2_trial_mat(i2_spike_counts >= 1);
        i2_spike_times = i2_time_mat(i2_spike_counts >= 1);
        trial_sorter = [t2(i2_spike_flags),choice(i2_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + i2_n_trial_counter;
        i2_sorted_trials = resorted_idcs(i2_spike_trials - i2_n_trial_counter);
        plot(sps(3+n_cols),i2_spike_times,i2_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',2,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = [0,1,1,0] .* range(xlim(sps(3))) * .1/2;
        ypatch = [.5,.5,i2_n_trials+.5,i2_n_trials+.5] + i2_n_trial_counter;
        patch(sps(3+n_cols),xpatch,ypatch,i2_clrs(ii,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        i2_n_trial_counter = i2_n_trial_counter + i2_n_trials;
        i2_boundaries(ii) = i2_n_trials;
    end
    
    % iterate through durations
    for tt = n_t : -1 : 1
        t2_flags = t2 == t_set(tt);
        t2_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            t2_flags;
        if sum(t2_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        t2_spike_counts = data.FR(t2_spike_flags,:);
        t2_spike_rates = conv2(...
            1,kernel.pdf,t2_spike_counts,'valid')' / psthbin * 1e3;
        t2_n_trials = size(t2_spike_counts,1);
        t2_n_tbins = post_s2_delay * psthbin;
        
        % T2-aligned, T1-split spike rates
        t2_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(t2_spike_flags) + ...
            t1(t2_spike_flags) + ...
            isi + ...
            t2(t2_spike_flags);
        t2_alignment_flags = ...
            valid_time >= t2_alignment_onset & ...
            valid_time < t2_alignment_onset + post_s2_delay;
        t2_chunk_flags = t2_alignment_flags;
        t2_spkrates = t2_spike_rates;
        t2_spkrates(~t2_alignment_flags') = nan;
        t2_spkrates = reshape(...
            t2_spkrates(t2_chunk_flags'),[t2_n_tbins,t2_n_trials])';
        
        % compute mean spike density function
        t2_mu = nanmean(t2_spkrates(:,time_flags),1);
        t2_std = nanstd(t2_spkrates(:,time_flags),0,1);
        t2_trials_throughtime = sum(~isnan(t2_spkrates),1);
        t2_sem = t2_std ./ sqrt(t2_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(t2_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        t2_xpatch = [flagged_time,fliplr(flagged_time)];
        t2_ypatch = [t2_mu(~nan_flags)-t2_sem(~nan_flags),...
            fliplr(t2_mu(~nan_flags)+t2_sem(~nan_flags))];
        patch_alpha = [t2_trials_throughtime(~nan_flags),...
            fliplr(t2_trials_throughtime(~nan_flags))].^0;
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(4),t2_xpatch,t2_ypatch,t2_clrs(tt,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        t2_xpatch = flagged_time(~nan_flags);
        t2_ypatch = t2_mu(~nan_flags);
        t2_ypatch(end) = nan;
        patch_alpha = t2_trials_throughtime(~nan_flags).^0;
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(4),t2_xpatch,t2_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',t2_clrs(tt,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(4),time2plot(onset_flags),t2_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',t2_clrs(tt,:));
        
        % plot T1 raster
        t2_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(t2_spike_flags) + ...
            t1(t2_spike_flags) + ...
            isi + ...
            t2(t2_spike_flags));
        t2_trial_idcs = (1 : t2_n_trials)' + t2_n_trial_counter;
        t2_trial_mat = repmat(t2_trial_idcs,1,n_paddedtimebins);
        t2_spike_trials = t2_trial_mat(t2_spike_counts >= 1);
        t2_spike_times = t2_time_mat(t2_spike_counts >= 1);
        trial_sorter = [t1(t2_spike_flags),prev_choices(t2_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + t2_n_trial_counter;
        t2_sorted_trials = resorted_idcs(t2_spike_trials - t2_n_trial_counter);
        plot(sps(4+n_cols),t2_spike_times,t2_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',2,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = [0,1,1,0] .* range(xlim(sps(4))) * .1/2;
        ypatch = [.5,.5,t2_n_trials+.5,t2_n_trials+.5] + t2_n_trial_counter;
        patch(sps(4+n_cols),xpatch,ypatch,t2_clrs(tt,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        t2_n_trial_counter = t2_n_trial_counter + t2_n_trials;
        t2_boundaries(tt) = t2_n_trials;
    end
    
    % iterate through choices
    for ii = 1 : n_choices
        choice_flags = choice == choice_set(ii);
        choice_spike_flags = ...
            valid_flags & ...
            neuron_flags & ...
            choice_flags;
        if sum(choice_spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        choice_spike_counts = data.FR(choice_spike_flags,:);
        choice_spike_rates = conv2(...
            1,kernel.pdf,choice_spike_counts,'valid')' / psthbin * 1e3;
        choice_n_trials = size(choice_spike_counts,1);
        choice_n_tbins = post_s2_delay * psthbin;
        
        % T2-aligned, I2-split spike rates
        choice_alignment_onset = ...
            pre_init_padding + ...
            pre_t1_delay(choice_spike_flags) + ...
            t1(choice_spike_flags) + ...
            isi + ...
            t2(choice_spike_flags);
        choice_alignment_flags = ...
            valid_time >= choice_alignment_onset & ...
            valid_time < choice_alignment_onset + post_s2_delay;
        choice_chunk_flags = choice_alignment_flags;
        choice_spkrates = choice_spike_rates;
        choice_spkrates(~choice_alignment_flags') = nan;
        choice_spkrates = reshape(...
            choice_spkrates(choice_chunk_flags'),[choice_n_tbins,choice_n_trials])';
        
        % compute mean spike density function
        choice_mu = nanmean(choice_spkrates(:,time_flags),1);
        choice_std = nanstd(choice_spkrates(:,time_flags),0,1);
        choice_trials_throughtime = sum(~isnan(choice_spkrates),1);
        choice_sem = choice_std ./ sqrt(choice_trials_throughtime);
        
        % flag current stimulus period
        nan_flags = isnan(choice_mu);
        onset_flags = time2plot <= 0 & [time2plot(2:end),nan] > 0;
        offset_flags = diff([nan_flags,true]) == 1;
        flagged_time = time2plot(~nan_flags);
        
        % patch s.e.m.
        choice_xpatch = [flagged_time,fliplr(flagged_time)];
        choice_ypatch = [choice_mu(~nan_flags)-choice_sem(~nan_flags),...
            fliplr(choice_mu(~nan_flags)+choice_sem(~nan_flags))];
        patch_alpha = [choice_trials_throughtime(~nan_flags),...
            fliplr(choice_trials_throughtime(~nan_flags))].^0;
        patch_alpha = patch_alpha * .25 + .05;
        patch(sps(5),choice_xpatch,choice_ypatch,choice_clrs(ii,:),...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'facealpha','interp',...
            'edgecolor','none');
        
        % patch average activity
        choice_xpatch = flagged_time(~nan_flags);
        choice_ypatch = choice_mu(~nan_flags);
        choice_ypatch(end) = nan;
        patch_alpha = choice_trials_throughtime(~nan_flags).^0;
        patch_alpha = patch_alpha * .95 + .05;
        patch(sps(5),choice_xpatch,choice_ypatch,0,...
            'facevertexalphadata',patch_alpha',...
            'alphadatamapping','none',...
            'edgealpha','interp',...
            'edgecolor',choice_clrs(ii,:),...
            'linewidth',1.5);
        
        % plot onset & offset
        plot(sps(5),time2plot(onset_flags),choice_mu(onset_flags),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',7.5,...
            'markerfacecolor','w',...
            'markeredgecolor',choice_clrs(ii,:));
        
        % plot I2 raster
        choice_time_mat = padded_time - (...
            pre_init_padding + ...
            pre_t1_delay(choice_spike_flags) + ...
            t1(choice_spike_flags) + ...
            isi + ...
            t2(choice_spike_flags));
        choice_trial_idcs = (1 : choice_n_trials)' + choice_n_trial_counter;
        choice_trial_mat = repmat(choice_trial_idcs,1,n_paddedtimebins);
        choice_spike_trials = choice_trial_mat(choice_spike_counts >= 1);
        choice_spike_times = choice_time_mat(choice_spike_counts >= 1);
        trial_sorter = [t2(choice_spike_flags),choice(choice_spike_flags)];
        [~,sorted_idcs] = sortrows(trial_sorter,[1,-2]);
        [~,resorted_idcs] = sortrows(sorted_idcs);
        resorted_idcs = resorted_idcs + choice_n_trial_counter;
        choice_sorted_trials = resorted_idcs(choice_spike_trials - choice_n_trial_counter);
        plot(sps(5+n_cols),choice_spike_times,choice_sorted_trials,...
            'color','k',...
            'marker',spike_marker,...
            'markersize',2,...
            'linestyle','none');
        
        % plot raster bands
        xpatch = [0,1,1,0] .* range(xlim(sps(5))) * .1/2;
        ypatch = [.5,.5,choice_n_trials+.5,choice_n_trials+.5] + choice_n_trial_counter;
        patch(sps(5+n_cols),xpatch,ypatch,choice_clrs(ii,:),...
            'linewidth',1.5,...
            'facealpha',.75,...
            'edgecolor','none');
        
        % update trial counters
        choice_n_trial_counter = choice_n_trial_counter + choice_n_trials;
        choice_boundaries(ii) = choice_n_trials;
    end
    
    % check if all conditions have trials
    if all(isnan(i1_boundaries)) || ...
            all(isnan(t2_boundaries)) || ...
            all(isnan(i2_boundaries)) || ...
            all(isnan(t2_boundaries)) || ...
            all(isnan(choice_boundaries))
        continue;
    end
    
    % axes updates
    set(sps(1+n_cols),...
        'ylim',[1,nansum(i1_boundaries)]+[-1,1]*.5,...
        'ytick',unique([1;cumsum(i1_boundaries,'omitnan')]));
    set(sps(2+n_cols),...
        'ylim',[1,nansum(t1_boundaries)]+[-1,1]*.5,...
        'ytick',unique(1+nansum(t1_boundaries)-[1;cumsum(t1_boundaries,'omitnan')]));
    set(sps(3+n_cols),...
        'ylim',[1,nansum(i2_boundaries)]+[-1,1]*.5,...
        'ytick',unique([1;cumsum(i2_boundaries,'omitnan')]));
    set(sps(4+n_cols),...
        'ylim',[1,nansum(t2_boundaries)]+[-1,1]*.5,...
        'ytick',unique(1+nansum(t2_boundaries)-[1;cumsum(t2_boundaries,'omitnan')]));
    set(sps(5+n_cols),...
        'ylim',[1,nansum(choice_boundaries)]+[-1,1]*.5,...
        'ytick',unique([1;cumsum(choice_boundaries,'omitnan')]));
    
    % axes linkage
    linkaxes(sps(1:n_cols),'y');
    
    % update y-axis limits
    yylim = [min([ylim(sps(1)),ylim(sps(2)),ylim(sps(3))]),...
        max([ylim(sps(1)),ylim(sps(2)),ylim(sps(3))])];
    yylim = 5 * [floor(yylim(1)/5),floor(yylim(2)/5)];
    if neurons2plot(nn) == 393
        yylim = yylim + [0,5];
    end
    yylim = max(yylim,[0,1]);
    set(sps(1:n_cols),...
        'ylim',yylim,...
        'ytick',yylim,...
        'clipping','off');
    
    % save figure
    if want2save
        try
            % save settings
            png_file = fullfile(raster_path,[get(fig,'name'),'.png']);
            print(fig,png_file,'-dpng','-r300','-painters');
            svg_file = fullfile(panel_path,[fig.Name,'.svg']);
            print(fig,svg_file,'-dsvg','-painters');
            close(fig);
        catch
            close(fig);
        end
    else
        pause(1);
        close(fig);
    end
end
