%% check 'main.m' has run (and run it if not)
toso2021_maincheck;

%% simulate behavior by an 'idealized' observer
toso2021_idealizedObserver;

%% choice GLM (logistic regression)

% design matrix
X = [t1,t2,i1,i2];
n_regressors = size(X,2);
n_coefficients = n_regressors + 1;

% feature normalization
Z = (X - nanmean(X)) ./ nanstd(X);

% preallocation
betas = nan(n_subjects,n_coefficients);

% iterate through subjects
for ss = 1 : n_subjects
    subject_flags = subjects == subject_set(ss);
    trial_flags = ...
        valid_flags & ...
        unique_flags & ...
        subject_flags;
    
    % fit GLM to each subject
    mdl = fitglm(Z(trial_flags,:),idealized_choice(trial_flags),'linear',...
        'predictorvars',{s1_lbl,s2_lbl,d1_lbl,d2_lbl},...
        'distribution','binomial',...
        'intercept',true);
    betas(ss,:) = mdl.Coefficients.Estimate;
end

% fit GLM to subject pool
mdl = fitglm(Z(valid_flags,:),idealized_choice(valid_flags),'linear',...
    'predictorvars',{'T1','T2','I1','I2'},...
    'distribution','binomial',...
    'intercept',true);
bigbetas = mdl.Coefficients.Estimate;
beta_s1 = bigbetas(2);
beta_s2 = bigbetas(3);
beta_labels = mdl.CoefficientNames;
beta_labels{1} = 'Intercept';

%% plot GLM coefficients
fig = figure(figopt,...
    'name','idealized_choice_GLM');
axes(axesopt.default,...
    'xlim',[0,n_coefficients+1],...
    'ylim',[-1,1]+[-1,1]*.05*2,...
    'xtick',1:n_coefficients,...
    'xticklabelrotation',0,...
    'xticklabel',beta_labels,...
    'clipping','off',...
    'plotboxaspectratio',[1,1,1]);
title(sprintf('%s>%s~Binomial(\\phi(\\betaX))',s2_lbl,s1_lbl));
xlabel('Regressor');
ylabel('Regression weight');

% iterate through coefficients
for bb = 1 : n_coefficients
    offset = ((1:n_subjects) - (n_subjects + 1) / 2) * .025 * range(xlim);
    
    % plot subject coefficients
    grapeplot(bb+offset,betas(:,bb),...
        'marker','o',...
        'markersize',8,...
        'markerfacecolor',subject_clr,...
        'markeredgecolor',[1,1,1],...
        'linewidth',1.5);
end

% plot animal-pool coefficients
p = stem(1:n_coefficients,bigbetas,...
    'color','k',...
    'marker','o',...
    'markersize',12,...
    'markerfacecolor','k',...
    'markeredgecolor','w',...
    'linewidth',1.5);
p.BaseLine.LineWidth = p.LineWidth;

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end