%% check 'main.m' has run (and run it if not)
toso2021_maincheck;

%% choice GLM (partial model)
mdl = fitglm([s1(valid_flags),s2(valid_flags)].*[1,1],...
    choice(valid_flags,:),'linear',...
    'predictorvars',{s1_lbl,s2_lbl},...
    'distribution','binomial',...
    'intercept',true);
betas = mdl.Coefficients.Estimate;
beta_0 = betas(1);
beta_s1 = betas(2);
beta_s2 = betas(3);

%% color limits specification

% color limits
clims = [0,1] + [+1,-1] * .1;

%% sampling scheme w/ S1-S2 pairwise performance

% transfer function
tfun = @(x) log(x);
invfun = @(x) exp(x);

% pair specification
s_pairs = [s1,s2];
s_pairset = unique(s_pairs(valid_flags,:),'rows');
n_s_pairs = size(s_pairset,1);

% preallocation
p_choice = nan(n_s_pairs,1);
n_trials_perpair = nan(n_s_pairs,1);

% iterate through S1-S2 pairs
for ii = 1 : n_s_pairs
    s_flags = all(s_pairs == s_pairset(ii,:),2);
    trial_flags = ...
        valid_flags & ...
        unique_flags & ...
        s_flags;
    if sum(trial_flags) == 0
        continue;
    end
    
    % compute average performance for the current pair
    p_choice(ii) = mean(choice(trial_flags));
    n_trials_perpair(ii) = sum(trial_flags);
end

% nan filtering
s_pairset = s_pairset(~isnan(p_choice),:);
p_choice = p_choice(~isnan(p_choice));

% figure & axes initialization
fig = figure(figopt,...
    'name','generalization_matrix_Si');
axes(axesopt.default,...
    'xlim',tfun([s_set(1),s_set(end)]) + [-1,1] * .1 * range(tfun(s_set)),...
    'ylim',tfun([s_set(1),s_set(end)]) + [-1,1] * .1 * range(tfun(s_set)),...
    'xtick',tfun(s_set),...
    'ytick',tfun(s_set),...
    'xticklabel',num2cell(s_set),...
    'yticklabel',num2cell(s_set),...
    'clim',clims,...
    'xscale','linear',...
    'yscale','linear');
xlabel(sprintf('%s (%s)',s1_lbl,s_units));
ylabel(sprintf('%s (%s)',s2_lbl,s_units));

% colorbar
cbar = colorbar(...
    'color','k',...
    'limits',clims,...
    'box',axesopt.default.box,...
    'linewidth',axesopt.default.linewidth,...
    'tickdirection','out',...
    'ticklength',unique(axesopt.default.ticklength),...
    'fontsize',axesopt.default.fontsize,...
    'ticks',unique([clims,.5]));
cbar.Label.String = sprintf('P(%s > %s)',s2_lbl,s1_lbl);
cbar.Label.Rotation = -90;
cbar.Label.VerticalAlignment = 'bottom';

% plot reference lines
plot(xlim,ylim,':k',...
    'linewidth',1);
plot(tfun([1,1]*median(s1(valid_flags))),ylim,':k',...
    'linewidth',1);
plot(xlim,tfun([1,1]*median(s2(valid_flags))),':k',...
    'linewidth',1);

% plot NSD lines
plot(tfun(s_set([1,end-2])),tfun(s_set([1+2,end])),':k',...
    'linewidth',1);
plot(tfun(s_set([1+2,end])),tfun(s_set([1,end-2])),':k',...
    'linewidth',1);

% plot decision boundary
x = linspace(min(s_pairs(:,1)),max(s_pairs(:,1)),1e3);
y = -beta_s1 / beta_s2 * x - beta_0 / beta_s2;
plot(tfun(x),tfun(y),'--k',...
    'linewidth',1.5);

% plot performance
scatter(...
    tfun(s_pairset(:,1)),...
    tfun(s_pairset(:,2)),...
    250,p_choice,'s','filled',...
    'markeredgecolor','k',...
    'linewidth',1.5);

% iterate through pairs
for ii = 1 : n_s_pairs
    if s_pairset(ii,2) > s_pairset(ii,1)
        vertical_gain = .865;
    else
        vertical_gain = 1.175;
    end
    
    % annotate performance
    text(tfun(s_pairset(ii,1) * 1.05),tfun(s_pairset(ii,2) * vertical_gain),...
        sprintf('%.0f%%',p_choice(ii)*100),...
        'color','k',...
        'fontsize',axesopt.default.fontsize,...
        'horizontalalignment','center',...
        'verticalalignment','middle');
end

% annotate NSD = 0
text(.95,.95,sprintf('%s = 0',nsd_lbl),...
    'units','normalized',...
    'color','k',...
    'rotation',45,...
    'fontsize',axesopt.default.fontsize,...
    'horizontalalignment','right',...
    'verticalalignment','bottom');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% contraction bias visualization

% figure & axes initialization
fig = figure(figopt,...
    'name','contraction_bias_Si');
ax = axes(axesopt.default,...
    'xlim',tfun([s_set(1),s_set(end)]) + [-1,1] * .1 * range(tfun(s_set)),...
    'ylim',tfun([s_set(1),s_set(end)]) + [-1,1] * .1 * range(tfun(s_set)),...
    'xtick',tfun(s_set),...
    'ytick',tfun(s_set),...
    'xticklabel',num2cell(s_set),...
    'yticklabel',num2cell(s_set),...
    'clim',clims,...
    'xscale','linear',...
    'yscale','linear');
xlabel(sprintf('%s (%s)',s1_lbl,s_units));
ylabel(sprintf('%s (%s)',s2_lbl,s_units));

% colorbar
cbar = colorbar(...
    'color','k',...
    'limits',clims,...
    'box',axesopt.default.box,...
    'linewidth',axesopt.default.linewidth,...
    'yaxislocation','right',...
    'location','eastoutside',...
    'tickdirection','out',...
    'ticklength',unique(axesopt.default.ticklength),...
    'fontsize',axesopt.default.fontsize,...
    'ticks',unique([clims,.5]));
cbar.Label.String = sprintf('P(%s > %s)',s2_lbl,s1_lbl);
cbar.Label.Rotation = -90;
cbar.Label.VerticalAlignment = 'bottom';

% plot hypothesized probability of reporting S2 > S1
si_x = linspace(invfun(min(xlim)),invfun(max(xlim)),1e2);
if strcmpi(task_str,'duration')
    beta = 5.05;
else
    beta = 5.85;
end
p_choice_mat = 1 ./ (1 + exp(-beta * (si_x' - si_x) ./ (si_x' + si_x)));
h = pcolor(tfun(si_x),tfun(si_x),p_choice_mat);
h.EdgeColor = 'none';
h.FaceColor = 'interp';

% plot reference lines
plot(xlim,ylim,':k',...
    'linewidth',1.5);

% compute <S1>
s1_avg = nanmedian(s1(valid_flags));

% plot expected value of the s1 prior distribution
plot(tfun([1,1]*s1_avg),ylim,':k',...
    'linewidth',1.5);

% plot performance
scatter(...
    tfun(s_pairset(:,1)),...
    tfun(s_pairset(:,2)),...
    250,p_choice,'s','filled',...
    'markeredgecolor','k',...
    'linewidth',1.5);

% iterate through pairs
for ii = 1 : n_s_pairs
    if s_pairset(ii,2) > s_pairset(ii,1)
        vertical_gain = .865;
        font_clr = 'k';
    else
        vertical_gain = 1.175;
        font_clr = 'w';
    end
    
    % annotate performance
    text(tfun(s_pairset(ii,1) * 1.05),tfun(s_pairset(ii,2) * vertical_gain),...
        sprintf('%.0f%%',p_choice(ii)*100),...
        'fontsize',axesopt.default.fontsize,...
        'color',font_clr,...
        'horizontalalignment','center',...
        'verticalalignment','middle');
end

% graphical object preallocation
p = gobjects(n_s_pairs,1);

% iterate through pairs
for ii = 1 : n_s_pairs
    
    % compute post-contraction percept
    s_dv = (s_pairset(ii,2) - si_x) ./ (s_pairset(ii,2) + si_x);
    p_choice_hypo = 1 ./ (1 + exp(-beta * s_dv));
    [~,idx] = min(abs(p_choice(ii) - p_choice_hypo));
    
    % plot post-contraction percept
    xpatch = linspace(s_pairset(ii,1),si_x(idx),1e3);
    ypatch = [repmat(s_pairset(ii,2),1,1e3-1),nan];
    cpatch = repmat(p_choice(ii),1,1e3);
    p(ii) = plot(tfun([s_pairset(ii,1),si_x(idx)]),[1,1]*tfun(s_pairset(ii,2)),...
        'color','k',...
        'linewidth',4.5);
    patch(tfun(xpatch),tfun(ypatch),ypatch,cpatch,...
        'edgecolor','interp',...
        'linewidth',1.5);
    scatter(tfun(si_x(idx)),tfun(s_pairset(ii,2)),...
        75,p_choice(ii),'o','filled',...
        'markeredgecolor','k',...
        'linewidth',1.5);
end

% annotate expected value of s1
text(tfun(s1_avg),max(ylim),...
    sprintf('<%s>',s1_lbl),...
    'fontsize',axesopt.default.fontsize,...
    'horizontalalignment','center',...
    'verticalalignment','bottom');

% annotate NSD = 0
text(.95,.95,sprintf('%s = 0',nsd_lbl),...
    'units','normalized',...
    'color','k',...
    'rotation',45,...
    'fontsize',axesopt.default.fontsize,...
    'horizontalalignment','right',...
    'verticalalignment','bottom');

% ui restacking
uistack(p,'bottom');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end