%% initialization
if ~exist('data','var')
    toso2021_wrapper;
end

%% ROI settings

% roi definition
roi = [0,isi] + [-1,1] * 0;
padded_roi = roi + [-1,1] * .05 * range(roi);
n_bins = range(padded_roi) / psthbin;
time = linspace(padded_roi(1),padded_roi(2),n_bins);

% preallocation
zscore_weights = nan(n_bins,n_neurons);
ref_psths = nan(n_bins,n_neurons);
psths = nan(n_bins,n_neurons,n_contrasts);

%% subject selection
subject_flags = ismember(subjects,subject_set);

%% construct isi-aligned psths

% iterate through neurons
for nn = 1 : n_neurons
    progressreport(nn,n_neurons,'parsing neural data');
    neuron_flags = data.NeuronNumb == flagged_neurons(nn);
    ref_spike_flags = ...
        valid_flags & ...
        subject_flags & ...
        neuron_flags;
    if sum(ref_spike_flags) == 0
        continue;
    end
    
    % fetch spike counts & compute spike rates
    ref_spike_counts = data.FR(ref_spike_flags,:);
    ref_spike_rates = data.SDF(ref_spike_flags,:);
    ref_n_trials = size(ref_spike_counts,1);

    % ISI-aligned spike rates
    ref_alignment = ...
        pre_init_padding + ...
        pre_s1_delay(ref_spike_flags) + ...
        t1(ref_spike_flags);
    ref_alignment_flags = ...
        padded_time >= ref_alignment + 0 & ...
        padded_time < ref_alignment + isi;
    ref_chunk_flags = ...
        padded_time >= ref_alignment + padded_roi(1) & ...
        padded_time < ref_alignment + padded_roi(2);
    ref_spkrates = ref_spike_rates';
    ref_spkrates(~ref_alignment_flags') = nan;
    ref_spkrates = reshape(...
        ref_spkrates(ref_chunk_flags'),[n_bins,ref_n_trials])';
    
    % compute observations weights
    zscore_weights(:,nn) = sum(~isnan(ref_spkrates));
    
    % compute mean spike density function
    ref_psths(:,nn) = nanmean(ref_spkrates,1);
 
    % iterate through contrasts
    for ii = 1 : n_contrasts
        contrast_flags = contrasts == contrast_set(ii);
        spike_flags = ...
            valid_flags & ...
            subject_flags & ...
            neuron_flags & ...
            contrast_flags;
        if sum(spike_flags) == 0
            continue;
        end
        
        % fetch spike counts & compute spike rates
        spike_counts = data.FR(spike_flags,:);
        spike_rates = data.SDF(spike_flags,:);
        n_trials = size(spike_counts,1);

        % ISI-aligned spike rates
        alignment_onset = ...
            pre_init_padding + ...
            pre_s1_delay(spike_flags) + ...
            t1(spike_flags);
        alignment_flags = ...
            padded_time >= alignment_onset + 0 & ...
            padded_time < alignment_onset + isi;
        chunk_flags = ...
            padded_time >= alignment_onset + padded_roi(1) & ...
            padded_time < alignment_onset + padded_roi(2);
        spkrates = spike_rates';
%         spkrates(~alignment_flags') = nan;
        spkrates = reshape(...
            spkrates(chunk_flags'),[n_bins,n_trials])';

        % compute mean spike density function
        psths(:,nn,ii) = nanmean(spkrates,1);
    end
end

%% normalization
mus = nanmean(ref_psths,1);
sigs = nanstd(ref_psths,0,1);

% z-scoring
zpsths = (psths - mus) ./ sigs;

%% plot overall modulation

% figure initialization
fig = figure(figopt,...
    'name',['average_activity_isi_',contrast_str]);

% axes initialization
xxtick = unique([0;roi';t_set]);
xxticklabel = num2cell(xxtick);
axes(axesopt.default,...
    'clipping','off',...
    'xlim',roi + [-1,1] * .05 * range(roi),...
    'ylim',[-.75,.5]+[-1,1]*.05*1.25,...
    'ytick',[-.75,0,.5]);
xlabel('Time since ISI onset (ms)');
ylabel('Firing rate (z-scored)');

% graphical object preallocation
p = gobjects(n_contrasts,1);
mu_gobjs = gobjects(n_contrasts,n_t);
sem_gobjs = gobjects(n_contrasts,n_t);

% zero lines
plot([1,1]*0,ylim,...
    'color','k',...
    'linestyle',':');
plot([1,1]*isi,ylim,...
    'color','k',...
    'linestyle',':');
plot(xlim,[1,1]*0,...
    'color','k',...
    'linestyle',':');

% iterate through contrasts
for ii = 1 : n_contrasts
    contrast_flags = contrasts == contrast_set(ii);
    trial_flags = ...
        valid_flags & ...
        contrast_flags;

    % compute modulation stats
    X = zpsths(:,:,ii);
    x_mu = nanmean(X,2);
    x_sig = nanstd(X,0,2);
    x_sem = x_sig / sqrt(n_neurons);
    
    % patch s.e.m.
    sem_xpatch = [time,fliplr(time)];
    sem_ypatch = [x_mu-x_sem;...
        flipud(x_mu+x_sem)]';
    sem_gobjs(ii,1) = patch(sem_xpatch,sem_ypatch,contrast_clrs(ii,:),...
        'facealpha',alphabounds_sem(end),...
        'edgecolor','none');
    
    % patch average activity
    mu_xpatch = time;
    mu_ypatch = x_mu';
    mu_ypatch(end) = nan;
    mu_gobjs(ii,1) = plot(mu_xpatch,mu_ypatch,...
        'color',contrast_clrs(ii,:),...
        'linewidth',1.5);
    
    % plot S1 offset
    s1_offset_flags = time <= 0 & [time(2:end),nan] > 0;
    p(ii) = plot(time(s1_offset_flags),x_mu(s1_offset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',7.5,...
        'markerfacecolor','w',...
        'markeredgecolor',contrast_clrs(ii,:));
    
    % plot S2 onset
    s2_onset_flags = time <= isi & [time(2:end),nan] > isi;
    plot(time(s2_onset_flags),x_mu(s2_onset_flags),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',sqrt(50),...
        'markerfacecolor',contrast_clrs(ii,:),...
        'markeredgecolor','none');
end

% ui restacking
uistack([mu_gobjs(isgraphics(mu_gobjs)); ...
    sem_gobjs(isgraphics(sem_gobjs))],'bottom');
uistack(p,'top');

% legend
p1 = plot([1,1]*max(xlim)*2,[1,1]*max(ylim)*2,...
    'linewidth',1.5,...
    'linestyle','none',...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','w',...
    'markeredgecolor','k');
p2 = plot([1,1]*max(xlim)*2,[1,1]*max(ylim)*2,...
    'linewidth',1.5,...
    'linestyle','none',...
    'marker','o',...
    'markersize',7.5,...
    'markerfacecolor','k',...
    'markeredgecolor','none');
legend([p1,p2],{'S_1 offset','S_2 onset'},...
    'fontsize',axesopt.default.fontsize*.9,...
    'location','southeast',...
    'box','off');

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end