%% initialization
if ~exist('data','var')
    toso2021_wrapper;
end

%% construct Ti-aligned, Ii-split psths
pre_padd = 500;
roi2use = [0,t_set(end-1)];
roi2plot = [-pre_padd,t_set(end)];
roi2use_n_bins = range(roi2use) * psthbin;
roi2plot_n_bins = range(roi2plot) * psthbin;
roi2use_time = linspace(roi2use(1),roi2use(2),roi2use_n_bins);
roi2plot_time = linspace(roi2plot(1),roi2plot(2),roi2plot_n_bins);
roi2use_flags = ...
    roi2plot_time >= roi2use(1) & ...
    roi2plot_time <= roi2use(2);

% preallocation
s1_psths = nan(roi2plot_n_bins,n_neurons,n_i);
s2_psths = nan(roi2plot_n_bins,n_neurons,n_i);

% iterate through neurons
for nn = 1 : n_neurons
    progressreport(nn,n_neurons,'parsing neural data');
    neuron_flags = data.NeuronNumb == flagged_neurons(nn);
    spike_flags = ...
        valid_flags & ...
        neuron_flags;
    
    % iterate through intensities
    for ii = 1 : n_i
        i1_flags = i1 == i_set(ii);
        i2_flags = i2 == i_set(ii);
        s1_spike_flags = ...
            spike_flags & ...
            i1_flags;
        s2_spike_flags = ...
            spike_flags & ...
            i2_flags;
        if sum(s1_spike_flags) == 0 || sum(s2_spike_flags) == 0
            continue;
        end
        
        % fetch T1-aligned spike counts & compute spike rates
        s1_spike_counts = data.FR(s1_spike_flags,:);
        s1_spike_rates = conv2(...
            1,kernel.pdf,s1_spike_counts,'valid')' / psthbin * 1e3;
        s1_n_trials = size(s1_spike_counts,1);
        
        % fetch T2-aligned spike counts & compute spike rates
        s2_spike_counts = data.FR(s2_spike_flags,:);
        s2_spike_rates = conv2(...
            1,kernel.pdf,s2_spike_counts,'valid')' / psthbin * 1e3;
        s2_n_trials = size(s2_spike_counts,1);
        
        % T1-aligned spike rates
        s1_alignment_offset = ...
            pre_init_padding + ...
            pre_t1_delay(s1_spike_flags);
        s1_alignment_flags = ...
            valid_time >= s1_alignment_offset + roi2plot(1) & ...
            valid_time < s1_alignment_offset + t1(s1_spike_flags);
        s1_chunk_flags = ...
            valid_time >= s1_alignment_offset + roi2plot(1) & ...
            valid_time < s1_alignment_offset + roi2plot(2);
        s1_spkrates = s1_spike_rates;
        s1_spkrates(~s1_alignment_flags') = nan;
        s1_spkrates = reshape(...
            s1_spkrates(s1_chunk_flags'),...
            [roi2plot_n_bins,s1_n_trials])';
        
        % T2-aligned spike rates
        s2_alignment = ...
            pre_init_padding + ...
            pre_t1_delay(s2_spike_flags) + ...
            t1(s2_spike_flags) + ...
            inter_t1t2_delay;
        s2_alignment_flags = ...
            valid_time >= s2_alignment + roi2plot(1) & ...
            valid_time < s2_alignment + t2(s2_spike_flags);
        s2_chunk_flags = ...
            valid_time >= s2_alignment + roi2plot(1) & ...
            valid_time < s2_alignment + roi2plot(2);
        s2_spkrates = s2_spike_rates;
        s2_spkrates(~s2_alignment_flags') = nan;
        s2_spkrates = reshape(...
            s2_spkrates(s2_chunk_flags'),...
            [roi2plot_n_bins,s2_n_trials])';
        
        % compute mean spike density functions
        s1_psths(:,nn,ii) = nanmean(s1_spkrates,1);
        s2_psths(:,nn,ii) = nanmean(s2_spkrates,1);
    end
end

% nan handling
% s1_psths(isnan(s1_psths)) = 0;
% s2_psths(isnan(s2_psths)) = 0;
% post_s2_psths(isnan(post_s2_psths)) = 0;

%% normalization

% z-score T1-aligned spike density functions
s1_mus = nanmean(s1_psths,[1,3]);
s1_sigs = nanstd(s1_psths,0,[1,3]);
s1_zpsths = (s1_psths - s1_mus) ./ s1_sigs;

% z-score T2-aligned spike density functions
s2_mus = nanmean(s2_psths,[1,3]);
s2_sigs = nanstd(s2_psths,0,[1,3]);
s2_zpsths = (s2_psths - s2_mus) ./ s2_sigs;

%% cross-condition concatenations

% concatenate T1-aligned psths across conditions
s1_concat_all = nan(roi2use_n_bins*n_i,n_neurons);
s1_concat_extr = nan(roi2use_n_bins*(n_i-1),n_neurons);
s1_concat_mode = nan(roi2use_n_bins,n_neurons);
s1_concat_diff = nan(roi2use_n_bins,n_neurons);
for nn = 1 : n_neurons
    nn_zpsths_all = s1_zpsths(roi2use_flags,nn,:);
    nn_zpsths_extr = s1_zpsths(roi2use_flags,nn,(1:n_i)~=i1_mode_idx);
    nn_zpsths_mode = s1_zpsths(roi2use_flags,nn,i1_mode_idx);
    nn_zpsths_diff = s1_zpsths(roi2use_flags,nn,end) - s1_zpsths(roi2use_flags,nn,1);
    s1_concat_all(:,nn) = nn_zpsths_all(:);
    s1_concat_extr(:,nn) = nn_zpsths_extr(:);
    s1_concat_mode(:,nn) = nn_zpsths_mode(:);
    s1_concat_diff(:,nn) = nn_zpsths_diff(:);
end

% concatenate T2-aligned psths across conditions
s2_concat_all = nan(roi2use_n_bins*n_i,n_neurons);
s2_concat_extr = nan(roi2use_n_bins*(n_i-1),n_neurons);
s2_concat_mode = nan(roi2use_n_bins,n_neurons);
s2_concat_diff = nan(roi2use_n_bins,n_neurons);
for nn = 1 : n_neurons
    nn_zpsths_all = s2_zpsths(roi2use_flags,nn,:);
    nn_zpsths_extr = s2_zpsths(roi2use_flags,nn,(1:n_i)~=i2_mode_idx);
    nn_zpsths_mode = s2_zpsths(roi2use_flags,nn,i2_mode_idx);
    nn_zpsths_diff = s2_zpsths(roi2use_flags,nn,end) - s2_zpsths(roi2use_flags,nn,1);
    s2_concat_all(:,nn) = nn_zpsths_all(:);
    s2_concat_extr(:,nn) = nn_zpsths_extr(:);
    s2_concat_mode(:,nn) = nn_zpsths_mode(:);
    s2_concat_diff(:,nn) = nn_zpsths_diff(:);
end

%% ICA

% training settings
ica_epoch_str = 's2';
ica_design_str = 'mode';
%   'all'   ->  vanilla ICA
%   'extr'  ->  pseudo-demixed ICA
%   'mode'  ->  robust ICA
ica_design = eval([ica_epoch_str,'_concat_',ica_design_str]);

% ICA
n_ics = n_neurons;
ricamdl = rica(ica_design,n_ics2use,...
    'iterationlimit',1e4,...
    'verbositylevel',1);
coeff = ricamdl.TransformWeights;

% reorder ICs by variance explained
s1_lat = nanvar(s1_concat_all * coeff)';
s2_lat = nanvar(s2_concat_all * coeff)';
[~,ica_idcs] = sort(eval([ica_epoch_str,'_lat']),'descend');
coeff = coeff(:,ica_idcs);
s1_exp_ica = s1_lat(ica_idcs) / sum(nanvar(s1_concat_all)) * 100;
s2_exp_ica = s2_lat(ica_idcs) / sum(nanvar(s2_concat_all)) * 100;

% preallocation
s1_score = nan(roi2plot_n_bins,n_ics,n_i);
s2_score = nan(roi2plot_n_bins,n_ics,n_i);

% iterate through intensities
for ii = 1 : n_i
    
    % project onto ICs
    s1_score(:,:,ii) = s1_zpsths(:,:,ii) * coeff;
    s2_score(:,:,ii) = s2_zpsths(:,:,ii) * coeff;
end

%% 3D trajectories in IC space (T1-aligned)
fig = figure(figopt,...
    'name',sprintf('pc_trajectories_t1'));
set(gca,...
    axesopt.default,...
    'xtick',0,...
    'ytick',0,...
    'ztick',0);
xlabel(sprintf('IC_{%s} %i\n%.1f%% variance',ica_epoch_str,1,s1_exp_ica(1)),...
    'horizontalalignment','center');
ylabel(sprintf('IC_{%s} %i\n%.1f%% variance',ica_epoch_str,2,s1_exp_ica(2)),...
    'horizontalalignment','center');
zlabel(sprintf('IC_{%s} %i\n%.1f%% variance',ica_epoch_str,3,s1_exp_ica(3)),...
    'horizontalalignment','center');

% iterate through intensities
for ii = 1 : n_i
    
    % plot T1-aligned trajectory
    plot3(s1_score(:,1,ii),...
        s1_score(:,2,ii),...
        s1_score(:,3,ii),...
        'color',i1_clrs(ii,:),...
        'linestyle','-',...
        'linewidth',1.5);
    
    % plot T1-aligned stimulus onset
    onset_flags = roi2plot_time <= 0 & ...
        [roi2plot_time(2:end),nan] > 0;
    plot3(s1_score(onset_flags,1,ii),...
        s1_score(onset_flags,2,ii),...
        s1_score(onset_flags,3,ii),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',5,...
        'markerfacecolor','w',...
        'markeredgecolor',i1_clrs(ii,:));
    
    % iterate through stimuli
    for tt = 1 : n_t
        
        % plot T1-aligned stimulus offset
        offset_flags = roi2plot_time < t_set(tt) & ...
            [roi2plot_time(2:end),nan] >= t_set(tt);
        plot3(s1_score(offset_flags,1,ii),...
            s1_score(offset_flags,2,ii),...
            s1_score(offset_flags,3,ii),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',6,...
            'markerfacecolor',i1_clrs(ii,:),...
            'markeredgecolor',i1_clrs(ii,:));
    end
end

% update axis
axis tight;
xlim(xlim + [-1,1] * .1 * range(xlim));
ylim(ylim + [-1,1] * .1 * range(ylim));
zlim(zlim + [-1,1] * .1 * range(zlim));
set(gca,...
    'xtick',xlim,...
    'ytick',ylim,...
    'ztick',zlim,...
    'xticklabel',{},...
    'yticklabel',{},...
    'zticklabel',{},...
    'xcolor','k',...
    'ycolor','k',...
    'zcolor','k');

% update axis
angle = 0;
view(angle,0);

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% 3D trajectories in IC space (T2-aligned)
fig = figure(figopt,...
    'name',sprintf('pc_trajectories_t2'));
set(gca,...
    axesopt.default,...
    'xtick',0,...
    'ytick',0,...
    'ztick',0);
xlabel(sprintf('IC_{%s} %i\n%.1f%% variance',ica_epoch_str,1,s2_exp_ica(1)),...
    'horizontalalignment','center');
ylabel(sprintf('IC_{%s} %i\n%.1f%% variance',ica_epoch_str,2,s2_exp_ica(2)),...
    'horizontalalignment','center');
zlabel(sprintf('IC_{%s} %i\n%.1f%% variance',ica_epoch_str,3,s2_exp_ica(3)),...
    'horizontalalignment','center');

% iterate through intensities
for ii = 1 : n_i
    
    % plot T2-aligned trajectory
    plot3(s2_score(:,1,ii),...
        s2_score(:,2,ii),...
        s2_score(:,3,ii),...
        'color',i2_clrs(ii,:),...
        'linestyle','-',...
        'linewidth',1.5);
    
    % plot T2-aligned stimulus onset
    onset_flags = roi2plot_time <= 0 & ...
        [roi2plot_time(2:end),nan] > 0;
    plot3(s2_score(onset_flags,1,ii),...
        s2_score(onset_flags,2,ii),...
        s2_score(onset_flags,3,ii),...
        'linewidth',1.5,...
        'marker','o',...
        'markersize',5,...
        'markerfacecolor','w',...
        'markeredgecolor',i2_clrs(ii,:));
    
    % iterate through stimuli
    for tt = 1 : n_t
        
        % plot T2-aligned stimulus offset
        offset_flags = roi2plot_time < t_set(tt) & ...
            [roi2plot_time(2:end),nan] >= t_set(tt);
        plot3(s2_score(offset_flags,1,ii),...
            s2_score(offset_flags,2,ii),...
            s2_score(offset_flags,3,ii),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',6,...
            'markerfacecolor',i2_clrs(ii,:),...
            'markeredgecolor',i2_clrs(ii,:));
    end
end

% update axis
axis tight;
xlim(xlim + [-1,1] * .1 * range(xlim));
ylim(ylim + [-1,1] * .1 * range(ylim));
zlim(zlim + [-1,1] * .1 * range(zlim));
set(gca,...
    'xtick',xlim,...
    'ytick',ylim,...
    'ztick',zlim,...
    'xticklabel',{},...
    'yticklabel',{},...
    'zticklabel',{},...
    'xcolor','k',...
    'ycolor','k',...
    'zcolor','k');

% update axis
angle = 0;
view(angle,0);

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% IC projections (T1-aligned)

% figure initialization
fig = figure(figopt,...
    'position',[1.8,41.8,766.4,740.8],...
    'name',sprintf('pc_projections_t1'));
n_ics2plot = 6;
sps = gobjects(n_ics2plot,1);
for ic = 1 : n_ics2plot
    sp_idx = ic * 2 - 1 - (ic > n_ics2plot / 2) * (n_ics2plot - 1);
    sps(ic) = subplot(n_ics2plot/2,2,sp_idx);
    xlabel(sps(ic),'Time since T_1 onset (s)');
    ylabel(sps(ic),sprintf('IC_{%s} %i\n%.1f%% variance',...
        ica_epoch_str,ic,s1_exp_ica(ic)));
end
xxtick = unique([roi2plot';0;t_set]);
xxticklabel = num2cell(xxtick);
xxticklabel(xxtick > 0 & xxtick < t_set(end)) = {''};
set(sps,...
    axesopt.default,...
    'xlim',roi2plot + [-1,1] * .05 * range(roi2plot),...
    'xtick',xxtick,...
    'xticklabel',xxticklabel,...
    'ylimspec','tight',...
    'plotboxaspectratio',[2,1,1]);

% link axes
linkaxes(sps,'x');

% iterate through pcs
for ic = 1 : n_ics2plot
    
    % graphical object preallocation
    p = gobjects(n_i,1);
    
    % iterate through intensities
    for ii = 1 : n_i
        
        % plot projection
        p(ii) = plot(sps(ic),roi2plot_time,...
            s1_score(:,ic,ii),...
            'color',i1_clrs(ii,:),...
            'linestyle','-',...
            'linewidth',1.5);
        
        % plot projection onset
        onset_flags = roi2plot_time <= 0 & ...
            [roi2plot_time(2:end),nan] > 0;
        plot(sps(ic),roi2plot_time(onset_flags),...
            s1_score(onset_flags,ic,ii),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',5,...
            'markerfacecolor','w',...
            'markeredgecolor',i1_clrs(ii,:));
        
        % iterate through stimuli
        for tt = 1 : n_t
            
            % plot projection offset
            offset_flags = roi2plot_time < t_set(tt) & ...
                [roi2plot_time(2:end),nan] >= t_set(tt);
            plot(sps(ic),roi2plot_time(offset_flags),...
                s1_score(offset_flags,ic,ii),...
                'linewidth',1.5,...
                'marker','o',...
                'markersize',6,...
                'markerfacecolor',i1_clrs(ii,:),...
                'markeredgecolor','none');
        end
    end
    
    % update axes
    set(sps(ic),...
        'ytick',unique([0,ylim(sps(ic))]),...
        'yticklabel',{'','0',''},...
        'ylim',ylim(sps(ic))+[-1,1]*.1*range(ylim(sps(ic))));
    
    % ui stacking
    uistack(p(:),'bottom');
end

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end

%% IC projections (T2-aligned)

% figure initialization
fig = figure(figopt,...
    'position',[769.8,41.8,766.4,740.8],...
    'name',sprintf('pc_projections_t2'));
n_ics2plot = 6;
sps = gobjects(n_ics2plot,1);
for ic = 1 : n_ics2plot
    sp_idx = ic * 2 - 1 - (ic > n_ics2plot / 2) * (n_ics2plot - 1);
    sps(ic) = subplot(n_ics2plot/2,2,sp_idx);
    xlabel(sps(ic),'Time since T_2 onset (s)');
    ylabel(sps(ic),sprintf('IC_{%s} %i\n%.1f%% variance',...
        ica_epoch_str,ic,s2_exp_ica(ic)));
end
xxtick = unique([roi2plot';0;t_set]);
xxticklabel = num2cell(xxtick);
xxticklabel(xxtick > 0 & xxtick < t_set(end)) = {''};
set(sps,...
    axesopt.default,...
    'xlim',roi2plot + [-1,1] * .05 * range(roi2plot),...
    'xtick',xxtick,...
    'xticklabel',xxticklabel,...
    'ylimspec','tight',...
    'plotboxaspectratio',[2,1,1]);

% link axes
linkaxes(sps,'x');

% iterate through pcs
for ic = 1 : n_ics2plot
    
    % graphical object preallocation
    p = gobjects(n_i,1);
    
    % iterate through intensities
    for ii = 1 : n_i
        
        % plot projection
        p(ii) = plot(sps(ic),roi2plot_time,...
            s2_score(:,ic,ii),...
            'color',i2_clrs(ii,:),...
            'linestyle','-',...
            'linewidth',1.5);
        
        % plot projection onset
        onset_flags = roi2plot_time <= 0 & ...
            [roi2plot_time(2:end),nan] > 0;
        plot(sps(ic),roi2plot_time(onset_flags),...
            s2_score(onset_flags,ic,ii),...
            'linewidth',1.5,...
            'marker','o',...
            'markersize',5,...
            'markerfacecolor','w',...
            'markeredgecolor',i2_clrs(ii,:));
        
        % iterate through stimuli
        for tt = 1 : n_t
            
            % plot projection offset
            offset_flags = roi2plot_time < t_set(tt) & ...
                [roi2plot_time(2:end),nan] >= t_set(tt);
            plot(sps(ic),roi2plot_time(offset_flags),...
                s2_score(offset_flags,ic,ii),...
                'linewidth',1.5,...
                'marker','o',...
                'markersize',6,...
                'markerfacecolor',i2_clrs(ii,:),...
                'markeredgecolor','none');
        end
    end
    
    % update axes
    set(sps(ic),...
        'ytick',unique([0,ylim(sps(ic))]),...
        'yticklabel',{'','0',''},...
        'ylim',ylim(sps(ic))+[-1,1]*.1*range(ylim(sps(ic))));
    
    % ui stacking
    uistack(p(:),'bottom');
end

% save figure
if want2save
    svg_file = fullfile(panel_path,[fig.Name,'.svg']);
    print(fig,svg_file,'-dsvg','-painters');
end